import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BookOpen } from 'lucide-react';
import { getBlogPosts } from '../../lib/api';

export const revalidate=900;
export const metadata:Metadata={title:'Travel Guides & Blog',description:'Safari planning guides, wildlife migration timing, and travel tips for Kenya, Tanzania, and Zanzibar.',alternates:{canonical:'/blog'}};
export default async function BlogPage(){const posts=await getBlogPosts();return <div className="max-w-7xl mx-auto px-4 sm:px-8 py-10 space-y-9"><section className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#142019] to-shell p-7 sm:p-10 text-center shadow-xl"><div className="max-w-3xl mx-auto space-y-4"><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-brand-soft"><BookOpen className="w-4 h-4"/>Safari planning guides</div><h1 className="font-serif-luxury text-3xl sm:text-5xl font-bold text-white">Plan with more confidence before you enquire.</h1><p className="text-base text-on-shell-muted leading-relaxed">Explore destination comparisons, seasonal considerations and practical safari planning advice for Kenya, Tanzania and the coast.</p></div></section>{posts.length?<div className="grid grid-cols-1 md:grid-cols-3 gap-7">{posts.map(post=><article key={post.id} className="group rounded-2xl bg-white border border-border-strong overflow-hidden hover:border-brand hover:shadow-md transition-all flex flex-col text-ink"><Link href={`/blog/${post.slug}`} className="text-left flex flex-col flex-1"><div className="aspect-[16/10] overflow-hidden bg-surface-muted relative"><Image src={post.featuredImage||'/images/catalog/mara-savannah.jpg'} alt={post.title} fill className="object-cover group-hover:scale-[1.03] transition-transform duration-500" sizes="(max-width:768px) 100vw,33vw"/></div><div className="p-6 space-y-3 flex-1"><div className="flex items-center gap-2 text-xs font-bold text-brand-deep"><span>{post.category}</span><span>·</span><span className="text-ink-subtle">{post.readingTime}</span></div><h2 className="font-serif-luxury text-xl font-bold text-ink-strong group-hover:text-brand-hover transition-colors">{post.title}</h2><p className="text-sm text-ink-muted leading-relaxed">{post.excerpt}</p></div><div className="px-6 pb-6 pt-4 flex items-center justify-between text-sm text-ink-subtle border-t border-border"><span>{post.author?.name}</span><span className="text-brand-deep font-bold flex items-center gap-1">Read guide <ArrowRight className="w-4 h-4"/></span></div></Link></article>)}</div>:<div className="rounded-3xl bg-white border border-border-strong p-8 text-center text-ink-muted">Blog content is temporarily unavailable from the catalog API.</div>}</div>}
