'use client';

import { useEffect, useMemo, useState } from 'react';
import { Inbox, X } from 'lucide-react';
import { AdminBlog, AdminDestinations, AdminHotels, AdminTours } from './admin/AdminCatalogSections';
import { AdminGrowth } from './admin/AdminGrowth';
import { AdminLayout, type AdminSection } from './admin/AdminLayout';
import { AdminOverview } from './admin/AdminOverview';
import { AdminSettings } from './admin/AdminSettings';
import { AdminTestimonials } from './admin/AdminTestimonials';

type AdminUser={id:string;email:string;name:string};
type CatalogKey='tours'|'destinations'|'hotels'|'blog'|'testimonials';
type AnyRecord=Record<string,any>;
const endpoints:Record<CatalogKey,string>={tours:'/api/admin/tours',destinations:'/api/admin/destinations',hotels:'/api/admin/hotels',blog:'/api/admin/blog',testimonials:'/api/admin/testimonials'};

async function api(path:string,options:RequestInit={}){const response=await fetch(`/api/backend${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body:any=null;try{body=await response.json()}catch{}if(!response.ok)throw new Error(body?.error||`Request failed (${response.status})`);return body;}

export function AdminPortal(){
 const[user,setUser]=useState<AdminUser|null>(null);const[authChecked,setAuthChecked]=useState(false);const[error,setError]=useState('');const[activeSection,setActiveSection]=useState<AdminSection>('overview');const[data,setData]=useState<Record<string,any>>({});
 useEffect(()=>{api('/api/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setAuthChecked(true))},[]);useEffect(()=>{if(user)refresh()},[user]);
 async function refresh(){setError('');try{const[enquiries,settings,...catalog]=await Promise.all([api('/api/enquiries'),api('/api/settings'),...Object.entries(endpoints).map(async([key,path])=>[key,await api(path)] as const)]);setData({enquiries,settings,...Object.fromEntries(catalog as any)})}catch(err:any){setError(err.message)}}
 async function login(formData:FormData){setError('');try{setUser(await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:formData.get('email'),password:formData.get('password')})}))}catch(err:any){setError(err.message)}}
 async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>undefined);setUser(null);setData({})}
 async function updateStatus(id:string,status:string){try{await api(`/api/enquiries/${id}/status`,{method:'PUT',body:JSON.stringify({status})});await refresh()}catch(err:any){setError(err.message)}}
 async function saveSettings(settings:AnyRecord){try{const saved=await api('/api/settings',{method:'PUT',body:JSON.stringify(settings)});setData(current=>({...current,settings:saved}))}catch(err:any){setError(err.message);throw err}}
 async function createRecord(key:CatalogKey,draft:AnyRecord){try{const created=await api(endpoints[key],{method:'POST',body:JSON.stringify(draft)});setData(current=>({...current,[key]:[created,...(current[key]||[])]}))}catch(err:any){setError(err.message);throw err}}
 async function updateRecord(key:CatalogKey,id:string,draft:AnyRecord){try{const saved=await api(`${endpoints[key]}/${id}`,{method:'PUT',body:JSON.stringify(draft)});setData(current=>({...current,[key]:(current[key]||[]).map((item:AnyRecord)=>item.id===id?saved:item)}))}catch(err:any){setError(err.message);throw err}}
 async function deleteRecord(key:CatalogKey,id:string){try{await api(`${endpoints[key]}/${id}`,{method:'DELETE'});setData(current=>({...current,[key]:(current[key]||[]).filter((item:AnyRecord)=>item.id!==id)}))}catch(err:any){setError(err.message);throw err}}
 const enquiries=data.enquiries||[];const counts=useMemo(()=>({enquiries:enquiries.length,newEnquiries:enquiries.filter((item:AnyRecord)=>item.status==='New').length,tours:data.tours?.length||0,hotels:data.hotels?.length||0,destinations:data.destinations?.length||0,blog:data.blog?.length||0,testimonials:data.testimonials?.length||0}),[data,enquiries]);
 if(!authChecked)return <div className="min-h-screen bg-[#f7f5ee] flex items-center justify-center p-6 text-sm text-[#707f74]">Checking admin session…</div>;
 if(!user)return <div className="min-h-screen bg-[#f7f5ee] flex items-center justify-center px-4 py-12"><div className="w-full max-w-md rounded-3xl border border-[#e8e4da] bg-white p-7 sm:p-9 shadow-xl"><div className="mb-7"><span className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-[#9e7120]">Authenticated access</span><h1 className="mt-1 font-serif-luxury text-3xl font-bold text-[#161f19]">Good Secrets admin</h1><p className="mt-2 text-sm text-[#707f74]">Sign in to manage enquiries, website content and growth reporting.</p></div><form action={login} className="space-y-4"><label className="block text-sm font-bold text-[#303e35]">Email<input type="email" name="email" required autoComplete="email" className="mt-1.5 w-full min-h-12 rounded-xl border border-[#d7d1c4] bg-[#faf8f2] px-4 text-[#161f19] outline-none focus:border-[#8a611d] focus:ring-2 focus:ring-[#8a611d]/20"/></label><label className="block text-sm font-bold text-[#303e35]">Password<input type="password" name="password" required autoComplete="current-password" className="mt-1.5 w-full min-h-12 rounded-xl border border-[#d7d1c4] bg-[#faf8f2] px-4 text-[#161f19] outline-none focus:border-[#8a611d] focus:ring-2 focus:ring-[#8a611d]/20"/></label>{error?<p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>:null}<button className="w-full min-h-12 rounded-xl bg-[#1b4332] text-white font-extrabold text-sm hover:bg-[#123326]">Sign in</button></form></div></div>;
 const common=(key:CatalogKey)=>({records:data[key]||[],onCreate:(draft:AnyRecord)=>createRecord(key,draft),onUpdate:(id:string,draft:AnyRecord)=>updateRecord(key,id,draft),onDelete:(id:string)=>deleteRecord(key,id),onError:setError});
 let section:React.ReactNode=null;
 if(activeSection==='overview')section=<AdminOverview tours={data.tours||[]} hotels={data.hotels||[]} enquiries={enquiries} whatsapp={data.settings?.contact?.whatsapp||'+254 729 000 410'} onGoToEnquiries={()=>setActiveSection('enquiries')} onGoToTours={()=>setActiveSection('tours')}/>;
 else if(activeSection==='growth')section=<AdminGrowth enquiries={enquiries}/>;
 else if(activeSection==='enquiries')section=<EnquiriesPanel enquiries={enquiries} onStatus={updateStatus}/>;
 else if(activeSection==='tours')section=<AdminTours {...common('tours')}/>;
 else if(activeSection==='hotels')section=<AdminHotels {...common('hotels')}/>;
 else if(activeSection==='destinations')section=<AdminDestinations {...common('destinations')}/>;
 else if(activeSection==='blog')section=<AdminBlog {...common('blog')} defaultAuthorName={user.name}/>;
 else if(activeSection==='testimonials')section=<AdminTestimonials testimonials={data.testimonials||[]} onCreate={draft=>createRecord('testimonials',draft)} onUpdate={(id,draft)=>updateRecord('testimonials',id,draft)} onDelete={id=>deleteRecord('testimonials',id)} onError={setError}/>;
 else section=data.settings?<AdminSettings settings={data.settings} onSave={saveSettings}/>:<div className="rounded-2xl border border-[#e8e4da] bg-white p-6 text-sm text-[#707f74]">Loading company settings…</div>;
 return <AdminLayout active={activeSection} onNavigate={value=>{setError('');setActiveSection(value)}} adminName={user.name} adminEmail={user.email} onLogout={logout} counts={counts}>{error?<div className="mb-6 flex items-center justify-between gap-3 p-4 rounded-xl bg-rose-50 border border-rose-200 text-sm text-rose-800"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error" className="text-rose-600 hover:text-rose-800"><X className="w-4 h-4"/></button></div>:null}{section}</AdminLayout>;
}

function EnquiriesPanel({enquiries,onStatus}:{enquiries:AnyRecord[];onStatus:(id:string,status:string)=>void}){return <div className="space-y-6"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.2em] text-[#9e7120]"><Inbox className="w-4 h-4"/>CRM</div><h1 className="mt-1 font-serif-luxury text-3xl font-bold text-[#161f19]">Enquiries</h1><p className="mt-2 text-sm text-[#707f74]">Review new leads and move each enquiry through the planning pipeline.</p></div><div className="overflow-hidden rounded-2xl border border-[#e8e4da] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#faf8f2] text-[11px] uppercase tracking-wider text-[#707f74]"><tr><th className="px-5 py-4">Lead</th><th className="px-5 py-4">Trip</th><th className="px-5 py-4">Created</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-[#eeebe2]">{enquiries.map(item=><tr key={item.id}><td className="px-5 py-4"><strong className="text-[#161f19]">{item.fullName}</strong><span className="block text-xs text-[#707f74] mt-1">{item.email}</span><span className="block text-xs text-[#707f74]">{item.phone}</span></td><td className="px-5 py-4 text-[#405046]">{item.tourTitle||item.hotelTitle||item.preferredDestination||item.safariType||'General enquiry'}<span className="block text-xs text-[#9a9184] mt-1">{item.hearAboutUs}</span></td><td className="px-5 py-4 text-[#707f74]">{new Date(item.createdAt).toLocaleDateString()}</td><td className="px-5 py-4"><select value={item.status} onChange={event=>onStatus(item.id,event.target.value)} className="min-h-10 rounded-xl border border-[#d7d1c4] bg-[#faf8f2] px-3 font-semibold text-[#303e35]">{['New','Contacted','Quoted','Confirmed','Cancelled'].map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></div></div>}
