'use client';

import { useEffect, useMemo, useState } from 'react';

type AdminUser={id:string;email:string;name:string};
type CatalogKey='tours'|'destinations'|'hotels'|'blog'|'testimonials';
type AnyRecord=Record<string,any>;
const endpoints:Record<CatalogKey,string>={tours:'/api/admin/tours',destinations:'/api/admin/destinations',hotels:'/api/admin/hotels',blog:'/api/admin/blog',testimonials:'/api/admin/testimonials'};

async function api(path:string,options:RequestInit={}){const response=await fetch(`/api/backend${path}`,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body:any=null;try{body=await response.json()}catch{}if(!response.ok)throw new Error(body?.error||`Request failed (${response.status})`);return body;}
function stripServerFields(record:AnyRecord){const{id,createdAt,updatedAt,viewsCount,...rest}=record;return rest;}
function labelOf(record:AnyRecord){return record.title||record.name||record.reviewerName||record.slug||record.id;}

export function AdminPortal(){
  const[user,setUser]=useState<AdminUser|null>(null);const[authChecked,setAuthChecked]=useState(false);const[error,setError]=useState('');const[tab,setTab]=useState<'dashboard'|'enquiries'|CatalogKey>('dashboard');const[data,setData]=useState<Record<string,AnyRecord[]>>({});const[editor,setEditor]=useState<{key:CatalogKey;id?:string;json:string}|null>(null);const[busy,setBusy]=useState(false);
  useEffect(()=>{api('/api/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setAuthChecked(true))},[]);
  useEffect(()=>{if(user)refresh()},[user]);
  async function refresh(){setError('');try{const results=await Promise.all([api('/api/enquiries'),...Object.entries(endpoints).map(async([key,path])=>[key,await api(path)] as const)]);setData({enquiries:results[0],...Object.fromEntries(results.slice(1) as any)});}catch(err:any){setError(err.message)}}
  async function login(formData:FormData){setError('');try{const logged=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:formData.get('email'),password:formData.get('password')})});setUser(logged);}catch(err:any){setError(err.message)}}
  async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>undefined);setUser(null);setData({});}
  async function updateStatus(id:string,status:string){try{await api(`/api/enquiries/${id}/status`,{method:'PUT',body:JSON.stringify({status})});refresh()}catch(err:any){setError(err.message)}}
  async function deleteRecord(key:CatalogKey,id:string){if(!confirm('Delete this record? This cannot be undone.'))return;try{await api(`${endpoints[key]}/${id}`,{method:'DELETE'});refresh()}catch(err:any){setError(err.message)}}
  function editRecord(key:CatalogKey,record:AnyRecord){setEditor({key,id:record.id,json:JSON.stringify(stripServerFields(record),null,2)})}
  function createFromExisting(key:CatalogKey){const sample=data[key]?.[0];if(!sample){setError('Create at least one record with the existing admin tools before using clone creation for this empty catalog.');return}const clone=stripServerFields(sample);const stamp=Date.now().toString().slice(-6);if(clone.slug)clone.slug=`copy-${stamp}-${clone.slug}`;if(clone.title)clone.title=`Copy of ${clone.title}`;if(clone.name)clone.name=`Copy of ${clone.name}`;if('published'in clone)clone.published=false;setEditor({key,json:JSON.stringify(clone,null,2)})}
  async function saveEditor(){if(!editor)return;setBusy(true);setError('');try{const payload=JSON.parse(editor.json);await api(editor.id?`${endpoints[editor.key]}/${editor.id}`:endpoints[editor.key],{method:editor.id?'PUT':'POST',body:JSON.stringify(payload)});setEditor(null);await refresh()}catch(err:any){setError(err.message||'Invalid JSON')}finally{setBusy(false)}}
  const counts=useMemo(()=>({enquiries:data.enquiries?.length||0,newLeads:data.enquiries?.filter((item)=>item.status==='New').length||0,quoted:data.enquiries?.filter((item)=>['Quoted','Confirmed'].includes(item.status)).length||0,confirmed:data.enquiries?.filter((item)=>item.status==='Confirmed').length||0}),[data]);
  if(!authChecked)return <div className="empty-state">Checking admin session…</div>;
  if(!user)return <div className="prose-card" style={{maxWidth:520,margin:'0 auto'}}><p className="eyebrow">Authenticated access</p><h2>Good Secrets admin</h2><form action={login} className="form-grid"><label className="full">Email<input type="email" name="email" required/></label><label className="full">Password<input type="password" name="password" required/></label>{error?<p className="form-error full">{error}</p>:null}<button className="button primary full">Sign in</button></form></div>;
  const catalogTabs:CatalogKey[]=['tours','destinations','hotels','blog','testimonials'];
  return <div className="admin-shell"><div className="admin-toolbar"><button className="button dark" onClick={()=>setTab('dashboard')}>Dashboard</button><button className="button secondary" onClick={()=>setTab('enquiries')}>Enquiries</button>{catalogTabs.map((key)=><button className="button secondary" key={key} onClick={()=>setTab(key)}>{key[0].toUpperCase()+key.slice(1)}</button>)}<button className="button secondary" onClick={refresh}>Refresh</button><button className="button secondary" onClick={logout}>Sign out</button></div>{error?<p className="form-error">{error}</p>:null}
    {tab==='dashboard'?<><div className="facts"><div className="fact"><span>Enquiries</span><strong>{counts.enquiries}</strong></div><div className="fact"><span>New leads</span><strong>{counts.newLeads}</strong></div><div className="fact"><span>Quoted+</span><strong>{counts.quoted}</strong></div><div className="fact"><span>Confirmed</span><strong>{counts.confirmed}</strong></div></div><div className="prose-card" style={{marginTop:20}}><h2>Catalog overview</h2><div className="facts">{catalogTabs.map((key)=><div className="fact" key={key}><span>{key}</span><strong>{data[key]?.length||0}</strong></div>)}</div></div></>:null}
    {tab==='enquiries'?<div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Lead</th><th>Trip</th><th>Created</th><th>Status</th></tr></thead><tbody>{data.enquiries?.map((item)=><tr key={item.id}><td><strong>{item.fullName}</strong><br/>{item.email}<br/>{item.phone}</td><td>{item.tourTitle||item.preferredDestination||item.safariType||'General enquiry'}<br/><small>{item.hearAboutUs}</small></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><select value={item.status} onChange={(event)=>updateStatus(item.id,event.target.value)}>{['New','Contacted','Quoted','Confirmed','Cancelled'].map((status)=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>:null}
    {catalogTabs.includes(tab as CatalogKey)?<div><div className="section-header"><div><h2>{(tab as string)[0].toUpperCase()+(tab as string).slice(1)}</h2><p>Edit full records as structured JSON. New records are created as unpublished clones so required nested fields remain valid.</p></div><button className="button primary" onClick={()=>createFromExisting(tab as CatalogKey)}>Clone new record</button></div><div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Record</th><th>Published</th><th>Actions</th></tr></thead><tbody>{data[tab]?.map((item)=><tr key={item.id}><td><strong>{labelOf(item)}</strong><br/><small>{item.slug}</small></td><td>{String(item.published??'—')}</td><td><button className="button secondary" onClick={()=>editRecord(tab as CatalogKey,item)}>Edit</button> <button className="button secondary" onClick={()=>deleteRecord(tab as CatalogKey,item.id)}>Delete</button></td></tr>)}</tbody></table></div></div>:null}
    {editor?<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>setEditor(null)}>×</button><p className="eyebrow">{editor.id?'Edit':'Create'} {editor.key}</p><h2>Structured record editor</h2><p>Keep the existing field names and data types. Backend validation remains authoritative.</p><textarea style={{width:'100%',minHeight:420,fontFamily:'monospace',fontSize:12}} value={editor.json} onChange={(event)=>setEditor({...editor,json:event.target.value})}/><div className="hero-actions"><button className="button primary" disabled={busy} onClick={saveEditor}>{busy?'Saving…':'Save record'}</button><button className="button secondary" onClick={()=>setEditor(null)}>Cancel</button></div></div></div>:null}
  </div>;
}
