'use client';

import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Send, ShieldCheck, Sparkles } from 'lucide-react';

type Choice={id:string;title:string;desc?:string;label?:string};
const destinationChoices:Choice[]=[{id:'Kenya',title:'Kenya',desc:'Maasai Mara, Amboseli, Rift Valley and more.'},{id:'Tanzania',title:'Tanzania',desc:'Serengeti, Ngorongoro, Tarangire and more.'},{id:'Zanzibar',title:'Zanzibar & Coast',desc:'Beach time, Stone Town and Indian Ocean stays.'},{id:'Combined',title:'Kenya + Tanzania',desc:'Combine both countries in one route.'},{id:'BushBeach',title:'Safari + Beach',desc:'Wildlife first, then time on the coast.'}];
const durationChoices:Choice[]=[{id:'1-3',title:'1–3 days',label:'Short escape',desc:'Useful for stopovers, extensions and short breaks.'},{id:'4-7',title:'4–7 days',label:'Classic safari',desc:'Enough time for a focused route through two or three areas.'},{id:'8-14',title:'8–14 days',label:'In-depth journey',desc:'More variety, slower pacing and easier cross-border combinations.'},{id:'15+',title:'15+ days',label:'Extended journey',desc:'For a broad safari, culture and coast itinerary.'}];
const travelerChoices:Choice[]=[{id:'Solo',title:'Solo traveler',desc:'Private or shared options can be discussed.'},{id:'Couple',title:'Couple',desc:'Romantic stays and a flexible private pace.'},{id:'Family',title:'Family',desc:'Family-friendly stays and practical pacing.'},{id:'Friends',title:'Friends / small group',desc:'A private vehicle and shared itinerary.'},{id:'Seniors',title:'Senior travelers',desc:'Comfortable pacing and suitable properties.'},{id:'Photography',title:'Photography focused',desc:'More time around light, sightings and positioning.'}];
const comfortChoices:Choice[]=[{id:'Midrange',title:'Comfortable midrange',desc:'Reliable lodges and camps with good comfort and value.'},{id:'Luxury',title:'Luxury',desc:'Smaller camps, strong locations and elevated service.'},{id:'Ultra Luxury',title:'Ultra-luxury',desc:'Top-tier private stays, fly-in options and highly personalized service.'}];
const experienceChoices=['Big 5 Tracking','Wildebeest Migration','Elephants & Kilimanjaro','Maasai & Samburu Culture','Hot Air Balloon Safari','Zanzibar Beach Relaxation','Rhino Sanctuary','Predators & Big Cats','Birdwatching & Rift Lakes','Walking Safaris','Photography','Bush Dining'];
const budgetChoices=['Not sure yet','Under $1,500','$1,500 – $3,500','$3,500 – $7,000','$7,000+'];

export function SafariBuilder(){const[step,setStep]=useState(1);const[destinations,setDestinations]=useState<string[]>(['Kenya']);const[duration,setDuration]=useState('4-7');const[travelerType,setTravelerType]=useState('Couple');const[comfort,setComfort]=useState('Luxury');const[experiences,setExperiences]=useState<string[]>(['Big 5 Tracking','Elephants & Kilimanjaro']);const[budget,setBudget]=useState('Not sure yet');const[status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');const[error,setError]=useState('');
 const choiceClass=(selected:boolean)=>`min-h-24 w-full p-4 sm:p-5 rounded-2xl border text-left transition-all ${selected?'bg-[#fdfaf2] border-brand-strong shadow-sm':'bg-surface-muted border-border-strong hover:border-brand-strong'}`;const nav='min-h-11 inline-flex items-center justify-center gap-2 px-5 rounded-xl text-sm font-bold';const input='w-full min-h-11 px-3.5 py-2.5 rounded-xl bg-white border border-border-strong text-sm text-ink-strong focus:border-brand-strong focus:outline-none';
 const toggle=(list:string[],set:(v:string[])=>void,id:string,keepOne=false)=>set(list.includes(id)?(keepOne&&list.length===1?list:list.filter(x=>x!==id)):[...list,id]);
 const single=(items:Choice[],value:string,set:(v:string)=>void,cols='sm:grid-cols-2')=><div className={`grid grid-cols-1 ${cols} gap-3`}>{items.map(item=>{const selected=value===item.id;return <button type="button" key={item.id} onClick={()=>set(item.id)} className={choiceClass(selected)}><div className="flex items-start justify-between gap-3"><div><span className="font-serif-luxury text-lg font-bold text-ink-strong block">{item.title}</span>{item.label&&<span className="text-xs font-bold text-brand-deep block mt-1">{item.label}</span>}</div><span className={`mt-0.5 w-5 h-5 shrink-0 rounded-full flex items-center justify-center ${selected?'bg-brand-strong text-white':'border border-[#a9a093]'}`}>{selected&&<Check className="w-3 h-3 stroke-[3]"/>}</span></div>{item.desc&&<span className="text-sm text-ink-muted mt-2 leading-relaxed block">{item.desc}</span>}</button>})}</div>;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending');setError('');const fd=new FormData(e.currentTarget);const durationDays=duration==='1-3'?3:duration==='4-7'?6:duration==='8-14'?10:15;const adults=travelerType==='Solo'?1:travelerType==='Couple'?2:4;const children=travelerType==='Family'?2:0;const payload={fullName:String(fd.get('fullName')||''),email:String(fd.get('email')||''),phone:String(fd.get('phone')||''),country:String(fd.get('country')||'Not specified'),travelDates:String(fd.get('travelMonth')||'Flexible'),durationDays,adults,children,preferredDestination:destinations.join(', '),safariType:`Custom ${comfort} Safari: ${experiences.join(', ')}`,budget,accommodationPreference:comfort,specialRequests:`Traveler profile: ${travelerType}. Desired experiences: ${experiences.join(', ')}. ${String(fd.get('specialRequests')||'')}`,hearAboutUs:'Custom Safari Builder'};try{const r=await fetch('/api/backend/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'Something went wrong sending your enquiry.')}setStatus('sent')}catch(err){setStatus('error');setError(err instanceof Error?err.message:'Something went wrong sending your enquiry.')}}
 if(status==='sent')return <section className="rounded-3xl bg-white border border-border-strong p-8 sm:p-10 max-w-4xl mx-auto text-center text-ink"><div className="w-16 h-16 rounded-full bg-action-soft text-action flex items-center justify-center mx-auto"><CheckCircle2 className="w-8 h-8"/></div><h2 className="font-serif-luxury text-3xl font-bold text-ink-strong mt-5">Your safari brief is with the team.</h2><p className="text-ink-muted mt-3 max-w-xl mx-auto">No booking or payment has been made. The next step is a human review of route, dates and availability.</p><button onClick={()=>{setStep(1);setStatus('idle')}} className={`${nav} mt-6 bg-surface-soft text-ink`}>Build another safari</button></section>;
 return <section id="custom-safari-builder" className="rounded-3xl bg-white border border-border-strong overflow-hidden shadow-xl p-5 sm:p-10 max-w-4xl mx-auto text-ink"><div className="mb-8"><div className="flex flex-wrap items-center justify-between gap-2 text-sm font-bold text-ink-muted mb-3"><span className="text-brand-deep">Step {step} of 6</span><span>{['','Destination','Duration','Travel party','Comfort','Experiences','Your plan'][step]}</span></div><div className="h-2.5 w-full bg-surface-soft rounded-full overflow-hidden"><div className="h-full bg-brand-strong transition-all duration-300 rounded-full" style={{width:`${step/6*100}%`}}/></div></div>
 {step===1&&<div className="space-y-6"><div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong">Where would you like to go?</h2><p className="text-base text-ink-muted mt-2">Choose one or combine several places. You can change this later.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{destinationChoices.map(item=>{const selected=destinations.includes(item.id);return <button type="button" key={item.id} onClick={()=>toggle(destinations,setDestinations,item.id,true)} className={choiceClass(selected)}><div className="flex items-start justify-between"><span className="font-serif-luxury text-lg font-bold text-ink-strong">{item.title}</span><span className={`w-5 h-5 rounded-full flex items-center justify-center ${selected?'bg-brand-strong text-white':'border border-[#a9a093]'}`}>{selected&&<Check className="w-3 h-3"/>}</span></div><span className="text-sm text-ink-muted mt-2 block">{item.desc}</span></button>})}</div><div className="flex justify-end"><button onClick={()=>setStep(2)} className={`${nav} bg-brand-strong text-white`}>Next: trip length <ArrowRight className="w-4 h-4"/></button></div></div>}
 {step===2&&<div className="space-y-6"><div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong">How long would you like to travel?</h2><p className="text-base text-ink-muted mt-2">Choose the closest range. The final itinerary can be shorter or longer.</p></div>{single(durationChoices,duration,setDuration)}<Nav back={()=>setStep(1)} next={()=>setStep(3)} nextLabel="Next: travelers"/></div>}
 {step===3&&<div className="space-y-6"><div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong">Who are you traveling with?</h2><p className="text-base text-ink-muted mt-2">This helps with room setup, vehicle planning and pacing.</p></div>{single(travelerChoices,travelerType,setTravelerType,'sm:grid-cols-3')}<Nav back={()=>setStep(2)} next={()=>setStep(4)} nextLabel="Next: comfort"/></div>}
 {step===4&&<div className="space-y-6"><div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong">What level of comfort suits you?</h2><p className="text-base text-ink-muted mt-2">This is a starting preference, not a fixed package.</p></div>{single(comfortChoices,comfort,setComfort,'sm:grid-cols-3')}<Nav back={()=>setStep(3)} next={()=>setStep(5)} nextLabel="Next: experiences"/></div>}
 {step===5&&<div className="space-y-6"><div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong">What do you most want to experience?</h2><p className="text-base text-ink-muted mt-2">Pick as many as you like. These choices help shape recommendations.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">{experienceChoices.map(exp=>{const selected=experiences.includes(exp);return <button type="button" key={exp} onClick={()=>toggle(experiences,setExperiences,exp)} className={`min-h-12 p-3 rounded-xl text-left border text-sm font-semibold flex items-center justify-between gap-2 ${selected?'bg-brand-strong text-white border-brand-strong':'bg-surface-muted text-ink border-border-strong hover:border-brand-strong'}`}><span>{exp}</span>{selected&&<Check className="w-4 h-4"/>}</button>})}</div><div className="pt-4 border-t border-border"><p className="text-sm font-bold text-ink mb-2">Approximate budget per person <span className="font-normal text-ink-subtle">(excluding international flights)</span></p><div className="grid sm:grid-cols-3 md:grid-cols-5 gap-2">{budgetChoices.map(b=><button type="button" key={b} onClick={()=>setBudget(b)} className={`min-h-11 rounded-xl border px-2 text-xs font-bold ${budget===b?'bg-brand-strong text-white border-brand-strong':'bg-surface-muted text-ink border-border-strong'}`}>{b}</button>)}</div></div><Nav back={()=>setStep(4)} next={()=>setStep(6)} nextLabel="Review my plan"/></div>}
 {step===6&&<form onSubmit={submit} className="space-y-6"><div><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-brand-deep"><Sparkles className="w-4 h-4"/>Your safari brief</div><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-ink-strong mt-2">One last step — where should we send the plan?</h2><p className="text-sm text-ink-muted mt-2">{destinations.join(', ')} · {duration} · {travelerType} · {comfort} · {budget}</p></div><div className="grid sm:grid-cols-2 gap-4"><label className="text-sm font-semibold">Full name *<input required name="fullName" autoComplete="name" className={input}/></label><label className="text-sm font-semibold">Email *<input required type="email" name="email" autoComplete="email" className={input}/></label><label className="text-sm font-semibold">Phone / WhatsApp *<input required name="phone" autoComplete="tel" className={input}/></label><label className="text-sm font-semibold">Country *<input required name="country" autoComplete="country-name" className={input}/></label><label className="text-sm font-semibold">Travel month<input name="travelMonth" placeholder="e.g. July 2027" className={input}/></label><label className="text-sm font-semibold">Anything else?<input name="specialRequests" className={input}/></label></div>{status==='error'&&<p className="rounded-xl bg-rose-50 border border-rose-200 p-3 text-sm text-danger">{error}</p>}<div className="rounded-2xl bg-surface-soft border border-border-strong p-4 flex gap-3 text-sm text-ink-muted"><ShieldCheck className="w-5 h-5 text-action shrink-0"/>Submitting this brief does not take payment or confirm a booking.</div><div className="flex flex-col sm:flex-row justify-between gap-3"><button type="button" onClick={()=>setStep(5)} className={`${nav} bg-surface-soft text-ink`}><ArrowLeft className="w-4 h-4"/>Back</button><button disabled={status==='sending'} className={`${nav} bg-brand-strong text-white`}><Send className="w-4 h-4"/>{status==='sending'?'Sending…':'Send my safari brief'}</button></div></form>}
 </section>}

function Nav({back,next,nextLabel}:{back:()=>void;next:()=>void;nextLabel:string}){return <div className="flex justify-between gap-3"><button type="button" onClick={back} className="min-h-11 inline-flex items-center justify-center gap-2 px-5 rounded-xl text-sm font-bold bg-surface-soft text-ink"><ArrowLeft className="w-4 h-4"/>Back</button><button type="button" onClick={next} className="min-h-11 inline-flex items-center justify-center gap-2 px-5 rounded-xl text-sm font-bold bg-brand-strong text-white">{nextLabel}<ArrowRight className="w-4 h-4"/></button></div>}
