import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Mail, MapPin, Phone, ShieldCheck, Star } from 'lucide-react';
import { EnquiryButton } from './EnquiryButton';
import { companyContact } from '../lib/site';

export function SiteFooter(){const link='min-h-9 inline-flex items-center text-sm text-ink-muted hover:text-brand-hover transition-colors';return <footer className="bg-page border-t border-border-strong text-ink-muted pt-14 pb-10"><div className="max-w-7xl mx-auto px-4 sm:px-8 space-y-10">
  <div className="grid grid-cols-1 lg:grid-cols-12 gap-9 pb-10 border-b border-border-strong"><div className="lg:col-span-5 space-y-5"><Link href="/" className="flex items-center gap-3"><Image src="/images/brand/logo.png" alt="Good Secrets Safaris" width={170} height={70} className="h-14 w-auto object-contain"/><span className="text-[11px] font-extrabold uppercase tracking-[.2em] text-brand-deep">KENYA · TANZANIA · ZANZIBAR</span></Link><p className="text-sm leading-relaxed max-w-md">Private East Africa safaris and coastal escapes shaped around your dates, interests and travel style.</p><div className="rounded-2xl border border-border-strong bg-white p-4 max-w-md"><div className="flex items-center gap-2 text-brand-deep"><Star className="w-4 h-4 fill-current"/><strong className="text-sm text-ink-strong">Independent traveler feedback</strong></div><p className="text-xs mt-2">Read independently published traveler feedback, then open the original platform listings for the current source of truth.</p><Link href="/reviews" className="mt-3 inline-flex items-center gap-1.5 text-sm font-bold text-brand-deep">See traveler reviews <ArrowRight className="w-4 h-4"/></Link></div><EnquiryButton label="Request a safari quote" className="min-h-11 inline-flex items-center gap-2 px-5 rounded-xl bg-brand-strong hover:bg-brand-hover text-white text-sm font-bold shadow-sm"/></div>
  <nav className="lg:col-span-7 grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-8"><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Safari styles</h2>{['Big 5','Great Migration','Family','Honeymoon','Luxury','Safari & Beach'].map(s=><Link key={s} className={link} href={`/safaris?travelStyle=${encodeURIComponent(s)}`}>{s}</Link>)}</div><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Destinations</h2><Link className={link} href="/destinations">Maasai Mara</Link><Link className={link} href="/destinations">Amboseli</Link><Link className={link} href="/destinations">Serengeti</Link><Link className={link} href="/destinations">Zanzibar</Link><Link className={link} href="/destinations">View all destinations</Link></div><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Plan with confidence</h2><Link className={link} href="/plan-with-us">How we plan your safari</Link><Link className={link} href="/guides/booking-safari-direct-local-operator">Booking direct: what to know</Link><Link className={link} href="/reviews">Traveler reviews</Link><Link className={link} href="/about">Meet Good Secrets</Link><Link className={link} href="/safari-builder">Safari builder</Link><Link className={link} href="/guides">Safari planning guides</Link><Link className={link} href="/blog">Travel magazine</Link><Link className={link} href="/contact">Contact</Link></div></nav></div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-sm"><a href={`mailto:${companyContact.email}`} className="min-h-11 flex items-center gap-2 hover:text-brand-hover"><Mail className="w-4 h-4 text-brand-deep"/>{companyContact.email}</a><a href={`tel:${companyContact.phone.replace(/\s/g,'')}`} className="min-h-11 flex items-center gap-2 hover:text-brand-hover"><Phone className="w-4 h-4 text-brand-deep"/>{companyContact.phone}</a><div className="min-h-11 flex items-center gap-2"><MapPin className="w-4 h-4 text-brand-deep shrink-0"/>{companyContact.address}</div></div>
  <div className="flex flex-wrap gap-3"><div className="min-h-11 inline-flex items-center gap-2.5 rounded-xl border border-border-strong bg-white px-3.5 py-2 text-xs font-bold text-ink-strong"><Image src="/images/brand/tra-badge.jpg" alt="" width={40} height={28} className="h-6 w-auto"/>Licensed by Kenya&apos;s Tourism Regulatory Authority</div><div className="min-h-11 inline-flex items-center gap-2.5 rounded-xl border border-border-strong bg-white px-3.5 py-2 text-xs font-bold text-ink-strong"><Image src="/images/brand/amref-badge.jpg" alt="" width={40} height={28} className="h-6 w-auto"/>AMREF Flying Doctors emergency medical cover</div></div>
  <div className="flex flex-col gap-4 border-t border-border-strong pt-6 text-xs sm:flex-row sm:items-end sm:justify-between"><div className="max-w-3xl"><div className="flex items-start gap-2"><ShieldCheck className="w-4 h-4 text-brand-deep shrink-0"/><span>Submitting an enquiry does not confirm a booking or take payment. Trip, payment and cancellation terms are provided before you choose to proceed.</span></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 font-semibold"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Website Terms</Link><Link href="/booking-conditions">Booking Conditions</Link></div></div><div>© {new Date().getFullYear()} Good Secrets Safaris. All rights reserved.</div></div>
</div></footer>}
