import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Facebook, Instagram, Linkedin, Mail, MapPin, Phone, ShieldCheck, Sparkles, Star, Youtube } from 'lucide-react';
import { EnquiryButton } from './EnquiryButton';
import { getDestinations, getSettings } from '../lib/api';
import { companyContact } from '../lib/site';

const trustBadges=[
  {logo:'/images/brand/tra-badge.jpg',label:"Licensed by Kenya's Tourism Regulatory Authority"},
  {logo:'/images/brand/amref-badge.jpg',label:'AMREF Flying Doctors emergency medical cover'}
];

export async function SiteFooter(){
  const[settings,destinations]=await Promise.all([getSettings(),getDestinations()]);
  const contact=settings?.contact||companyContact;
  const description=settings?.description||'Private East Africa safaris and coastal escapes shaped around your dates, interests and travel style.';
  const socials=settings?.social||{};
  const linkClass='min-h-9 inline-flex items-center text-sm text-ink-muted hover:text-brand-hover transition-colors text-left';
  return <footer id="main-footer" className="bg-page border-t border-border-strong text-ink-muted pt-14 pb-10"><div className="max-w-7xl mx-auto px-4 sm:px-8 space-y-10">
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-9 pb-10 border-b border-border-strong">
      <div className="min-w-0 lg:col-span-5 space-y-5"><Link href="/" aria-label="Good Secrets Safaris home" className="flex items-center gap-3 text-left rounded-xl"><Image src="/images/brand/logo.png" alt="Good Secrets Safaris" width={170} height={70} className="h-14 w-auto object-contain"/><span className="text-[11px] font-extrabold uppercase tracking-[0.2em] text-brand-deep block">KENYA · TANZANIA · ZANZIBAR</span></Link><p className="text-sm text-ink-muted leading-relaxed max-w-md">{description}</p><div className="rounded-2xl border border-border-strong bg-white p-4 max-w-md"><div className="flex items-center gap-2 text-brand-deep"><Star className="w-4 h-4 fill-current"/><strong className="text-sm text-ink-strong">Independent traveler feedback</strong></div><p className="text-xs text-ink-muted mt-2">Read independently published traveler feedback, then open the original platform listings for the current source of truth.</p><Link href="/reviews" className="mt-3 inline-flex items-center gap-1.5 text-sm font-bold text-brand-deep hover:text-ink-strong">See traveler reviews <ArrowRight className="w-4 h-4"/></Link></div><EnquiryButton label="Request a safari quote" className="min-h-11 inline-flex items-center gap-2 px-5 rounded-xl bg-brand-strong hover:bg-brand-hover text-white text-sm font-bold shadow-sm"/><div className="flex items-center gap-2 pt-1">{socials.instagram&&<a href={socials.instagram} target="_blank" rel="noopener noreferrer" className="min-w-11 min-h-11 rounded-xl bg-white text-ink-muted hover:text-brand-hover flex items-center justify-center border border-border-strong" aria-label="Good Secrets Safaris on Instagram"><Instagram className="w-4 h-4"/></a>}{socials.facebook&&<a href={socials.facebook} target="_blank" rel="noopener noreferrer" className="min-w-11 min-h-11 rounded-xl bg-white text-ink-muted hover:text-brand-hover flex items-center justify-center border border-border-strong" aria-label="Good Secrets Safaris on Facebook"><Facebook className="w-4 h-4"/></a>}{socials.youtube&&<a href={socials.youtube} target="_blank" rel="noopener noreferrer" className="min-w-11 min-h-11 rounded-xl bg-white text-ink-muted hover:text-brand-hover flex items-center justify-center border border-border-strong" aria-label="Good Secrets Safaris on YouTube"><Youtube className="w-4 h-4"/></a>}{socials.linkedin&&<a href={socials.linkedin} target="_blank" rel="noopener noreferrer" className="min-w-11 min-h-11 rounded-xl bg-white text-ink-muted hover:text-brand-hover flex items-center justify-center border border-border-strong" aria-label="Good Secrets Safaris on LinkedIn"><Linkedin className="w-4 h-4"/></a>}</div></div>
      <nav className="lg:col-span-7 grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-8" aria-label="Footer navigation"><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Safari styles</h2><ul>{['Big 5','Great Migration','Family','Honeymoon','Luxury','Safari & Beach'].map(style=><li key={style}><Link href={`/safaris?travelStyle=${encodeURIComponent(style)}`} className={linkClass}>{style}</Link></li>)}</ul></div><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Destinations</h2><ul>{destinations.slice(0,6).map(d=><li key={d.id}><Link href={`/destinations/${d.slug}`} className={linkClass}>{d.name}</Link></li>)}</ul></div><div><h2 className="text-xs font-extrabold uppercase tracking-wider text-ink-strong mb-2">Plan with confidence</h2><ul><li><Link href="/plan-with-us" className={linkClass}>How we plan your safari</Link></li><li><Link href="/guides/booking-safari-direct-local-operator" className={linkClass}>Booking direct: what to know</Link></li><li><Link href="/reviews" className={linkClass}>Traveler reviews</Link></li><li><Link href="/about" className={linkClass}>Meet Good Secrets</Link></li><li><Link href="/safari-builder" className={linkClass}>Safari builder</Link></li><li><Link href="/guides" className={linkClass}>Safari planning guides</Link></li><li><Link href="/blog" className={linkClass}>Travel magazine</Link></li><li><Link href="/contact" className={linkClass}>Contact</Link></li></ul></div></nav>
    </div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-sm text-ink-muted"><a href={`mailto:${contact.email}`} className="min-h-11 flex items-center gap-2 rounded-xl hover:text-brand-hover"><Mail className="w-4 h-4 text-brand-deep"/><span className="break-all">{contact.email}</span></a><a href={`tel:${contact.phone}`} className="min-h-11 flex items-center gap-2 rounded-xl hover:text-brand-hover"><Phone className="w-4 h-4 text-brand-deep"/>{contact.phone}</a><div className="min-h-11 flex items-center gap-2"><MapPin className="w-4 h-4 text-brand-deep shrink-0"/>{contact.address}</div></div>
    <div className="flex flex-wrap gap-3">{trustBadges.map(({logo,label})=><div key={label} className="min-h-11 inline-flex items-center gap-2.5 rounded-xl border border-border-strong bg-white px-3.5 py-2 text-xs font-bold text-ink-strong"><Image src={logo} alt="" aria-hidden="true" width={40} height={28} className="h-6 w-auto object-contain shrink-0"/><span>{label}</span></div>)}</div>
    <div className="flex flex-col gap-4 border-t border-border-strong pt-6 text-xs text-ink-muted sm:flex-row sm:items-end sm:justify-between"><div className="max-w-3xl"><div className="flex items-start gap-2"><ShieldCheck className="w-4 h-4 text-brand-deep shrink-0"/><span>Submitting an enquiry does not confirm a booking or take payment. Trip, payment and cancellation terms are provided before you choose to proceed.</span></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 font-semibold"><Link href="/privacy" className="hover:text-brand-hover">Privacy Policy</Link><Link href="/terms" className="hover:text-brand-hover">Website Terms</Link><Link href="/booking-conditions" className="hover:text-brand-hover">Booking Conditions</Link></div></div><div className="sm:text-right">© {new Date().getFullYear()} Good Secrets Safaris. All rights reserved.</div></div>
  </div></footer>
}
