import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, CalendarDays, Camera, Check, CircleHelp, Clock, Compass, ExternalLink, Map, MapPin, MessageCircle, ShieldCheck, Sparkles, Star, X } from 'lucide-react';
import { DynamicPricingTable } from '../../../components/DynamicPricingTable';
import { EnquiryButton } from '../../../components/EnquiryButton';
import { ItineraryTimeline } from '../../../components/ItineraryTimeline';
import { RelatedPlanningGuides } from '../../../components/RelatedPlanningGuides';
import { ShortlistButton } from '../../../components/ShortlistButton';
import { TourDecisionSummary } from '../../../components/TourDecisionSummary';
import { TourGallery } from '../../../components/TourGallery';
import { TourRouteMap } from '../../../components/TourRouteMap';
import { getTourBySlug, getTours } from '../../../lib/api';
import { getTourGuideRecommendations } from '../../../lib/guideRecommendations';
import { getRouteReviewStories, sourceUrl } from '../../../lib/reviewStories';
import { siteUrl } from '../../../lib/site';

export const revalidate = 900;
export const dynamicParams = true;
export async function generateStaticParams() { return (await getTours()).map(tour => ({ slug: tour.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const tour = await getTourBySlug(slug);
  if (!tour) return {};
  return { title: tour.seo?.title || tour.title, description: tour.seo?.description || tour.shortDescription, alternates: { canonical: `/safaris/${tour.slug}` }, openGraph: { title: tour.title, description: tour.shortDescription, url: `/safaris/${tour.slug}`, images: [tour.images?.[0] || '/images/catalog/mara-savannah.jpg'] } };
}

export default async function SafariDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const tour = await getTourBySlug(slug);
  if (!tour) notFound();
  const image = tour.images?.[0] || '/images/catalog/mara-savannah.jpg';
  const price = tour.sharingPrice || tour.priceFrom;
  const includedItems = [...(tour.includedServices || []), ...(tour.includedActivities || [])];
  const excludedItems = tour.exclusions || [];
  const routeStories = getRouteReviewStories(tour.destinations || []);
  const planningGuides = getTourGuideRecommendations(tour);
  const url = siteUrl(`/safaris/${tour.slug}`);
  const schema = [
    { '@context': 'https://schema.org', '@type': 'TouristTrip', name: tour.title, description: tour.shortDescription, touristType: tour.travelStyles, itinerary: tour.destinations?.join(' → '), image: siteUrl(image), url },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl('/') }, { '@type': 'ListItem', position: 2, name: 'Safaris', item: siteUrl('/safaris') }, { '@type': 'ListItem', position: 3, name: tour.title, item: url }] },
  ];
  const sectionLinks = [['overview', 'Overview', Compass], ['itinerary', 'Itinerary', CalendarDays], ['route', 'Route', Map], ['inclusions', 'Inclusions', Check], ['gallery', 'Gallery', Camera], ['pricing', 'Pricing', Sparkles], ['faqs', 'FAQs', CircleHelp]] as const;
  const sectionOffsetClass = 'scroll-mt-44 sm:scroll-mt-52';

  return <div className="pb-28 lg:pb-12">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="relative min-h-[440px] sm:min-h-[520px] lg:min-h-[570px] overflow-hidden bg-shell"><Image src={image} alt={`${tour.title} safari`} fill priority className="object-cover" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-t from-shell/95 via-shell/35 to-black/25" /><div className="relative max-w-7xl mx-auto px-4 sm:px-8 pt-6 pb-10 min-h-[440px] sm:min-h-[520px] lg:min-h-[570px] flex flex-col justify-between"><div className="flex items-center justify-between gap-3"><Link href="/safaris" className="min-h-11 inline-flex items-center gap-2 rounded-full bg-black/45 px-4 text-sm font-semibold text-white backdrop-blur-sm border border-white/20 hover:bg-black/60"><ArrowLeft className="w-4 h-4" />All safaris</Link><ShortlistButton safari={{ id: tour.id, title: tour.title, slug: tour.slug, image, durationLabel: tour.durationLabel, country: tour.country, priceFrom: tour.priceFrom }} /></div><div className="max-w-3xl">{tour.featured || tour.popular ? <span className="inline-flex rounded-full bg-action px-3 py-1.5 text-xs font-bold text-white shadow-sm mb-4">{tour.popular ? 'Popular Choice' : 'Featured Safari'}</span> : null}<h1 className="font-serif-luxury text-3xl sm:text-5xl lg:text-6xl font-bold text-white leading-[1.08] sm:leading-[1.05] break-words">{tour.title}</h1><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-white/95"><span className="inline-flex items-center gap-1.5"><Clock className="w-4 h-4 text-brand-soft" />{tour.durationLabel}</span><span className="inline-flex items-center gap-1.5"><MapPin className="w-4 h-4 text-brand-soft" />{tour.country}</span></div></div></div></section>

    <div className="sticky top-[68px] sm:top-[112px] z-30 border-y border-border-strong bg-page/98 backdrop-blur-xl shadow-[0_6px_20px_rgba(15,23,18,0.10)]"><div className="max-w-7xl mx-auto px-2 sm:px-5 lg:px-6 flex items-center gap-2"><nav aria-label="Tour sections" className="min-w-0 flex-1 flex items-center overflow-x-auto scrollbar-hide py-1">{sectionLinks.map(([id, label, Icon]) => <a key={id} href={`#${id}`} className="group shrink-0 min-h-12 px-3 sm:px-4 inline-flex items-center justify-center gap-2 rounded-lg text-xs sm:text-sm font-semibold text-ink-muted hover:text-brand-deep hover:bg-surface-soft transition-colors"><Icon className="w-[18px] h-[18px] shrink-0 text-ink-muted group-hover:text-brand-deep" aria-hidden="true" /><span>{label}</span></a>)}</nav><aside className="hidden xl:flex shrink-0 items-center gap-3 my-2 ml-2 rounded-xl border border-border-strong bg-white px-3 py-2 shadow-sm text-ink"><div className="min-w-[106px] leading-tight"><span className="block text-[10px] font-bold uppercase tracking-wider text-brand-deep">From</span><strong className="font-serif-luxury text-lg text-ink-strong">{tour.currency === 'KES' ? 'KES ' : '$'}{Number(price).toLocaleString()}</strong><span className="block text-[10px] text-ink-muted mt-0.5">Per person sharing</span></div><EnquiryButton label="Request This Safari" tourTitle={tour.title} className="min-h-11 whitespace-nowrap rounded-xl bg-action hover:bg-action-strong px-5 text-sm font-extrabold text-white shadow-sm" /></aside></div></div>

    <div className="relative z-10 bg-surface-soft border-b border-border-strong"><div className="max-w-7xl mx-auto px-4 sm:px-8 py-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 text-ink-strong"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm"><span className="inline-flex gap-2 items-center font-semibold text-action"><ShieldCheck className="w-4 h-4" />No payment required to enquire</span><span className="text-ink-muted">This itinerary can be tailored around your dates, pace and stay preferences.</span></div><div className="flex flex-wrap gap-x-4 gap-y-2"><Link href="/reviews" className="text-sm font-bold text-brand-deep hover:text-ink-strong">Reviews of Good Secrets Safaris</Link><Link href="/plan-with-us" className="text-sm font-bold text-brand-deep hover:text-ink-strong">How we plan your safari</Link></div></div></div>

    <TourDecisionSummary tour={tour} />

    <main className="max-w-7xl mx-auto px-4 sm:px-8 py-8 sm:py-12 space-y-14">
      <section id="overview" className={`${sectionOffsetClass} grid lg:grid-cols-12 gap-8 lg:gap-12 items-start`}><div className="min-w-0 lg:col-span-5 space-y-5"><div><span className="text-xs font-bold uppercase tracking-wider text-brand-soft">The experience</span><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">Safari overview</h2></div><p className="text-base text-on-shell-muted leading-relaxed whitespace-pre-line break-words">{tour.fullDescription || tour.shortDescription}</p><div className="grid grid-cols-2 gap-3 pt-2"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><Clock className="w-5 h-5 text-brand-soft mb-2" /><span className="text-xs text-on-shell-subtle block">Duration</span><strong className="text-sm text-white">{tour.durationLabel}</strong></div><div className="rounded-xl border border-white/10 bg-white/5 p-3"><Compass className="w-5 h-5 text-brand-soft mb-2" /><span className="text-xs text-on-shell-subtle block">Travel style</span><strong className="text-sm text-white">{tour.travelStyles?.[0] || 'Tailor-made'}</strong></div></div></div><div id="gallery" className={`min-w-0 ${sectionOffsetClass} lg:col-span-7`}><TourGallery images={tour.images || []} title={tour.title} /></div></section>

      {routeStories.length ? <section className="space-y-6" aria-labelledby="route-stories-heading"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-3"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Independent traveller feedback</span><h2 id="route-stories-heading" className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">Traveller stories from this route</h2><p className="text-sm text-on-shell-muted mt-2 max-w-3xl">These travelers reviewed Good Secrets Safaris trips that visited one or more places included in this itinerary. They are not reviews of this exact safari package.</p></div><Link href="/reviews" className="text-sm font-bold text-brand-soft hover:text-white whitespace-nowrap">See all independent reviews →</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{routeStories.map((review, index) => <a key={`${review.platform}-${review.reviewer}-${index}`} href={sourceUrl(review.platform)} target="_blank" rel="noopener noreferrer" className="group rounded-2xl border border-white/10 bg-white/5 p-5 transition hover:border-brand-strong hover:bg-white/[0.07]"><div className="flex items-center justify-between gap-3"><span className="text-xs font-extrabold uppercase tracking-wider text-brand-soft">{review.platform}</span><ExternalLink className="w-4 h-4 text-on-shell-subtle group-hover:text-white" /></div><div className="mt-3 flex text-amber-500" aria-label={`${review.rating} out of 5 stars`}>{Array.from({ length: review.rating }).map((_, starIndex) => <Star key={starIndex} className="w-4 h-4 fill-current" />)}</div><h3 className="font-serif-luxury text-lg font-bold text-white mt-3">{review.title}</h3><blockquote className="text-sm italic text-on-shell-muted leading-relaxed mt-2">“{review.excerpt}”</blockquote><div className="mt-4 flex flex-wrap gap-1.5">{review.destinations.filter(place => (tour.destinations || []).some(tourPlace => tourPlace.toLowerCase().includes(place.toLowerCase().replace('maasai', 'masai')) || place.toLowerCase().includes(tourPlace.toLowerCase().replace('maasai', 'masai')))).slice(0, 3).map(place => <span key={place} className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[11px] font-semibold text-on-shell-muted">{place}</span>)}</div><div className="mt-4 pt-4 border-t border-white/10"><strong className="text-sm text-white">{review.reviewer}</strong><span className="ml-2 text-xs text-on-shell-subtle">{review.date}</span><span className="mt-1 block text-xs font-bold text-brand-soft">Read the original review →</span></div></a>)}</div></section> : null}

      <section id="itinerary" className={sectionOffsetClass}><ItineraryTimeline itinerary={tour.itinerary || []} /></section>
      <section id="route" className={`${sectionOffsetClass} space-y-5`}><div><span className="text-xs font-bold uppercase tracking-wider text-brand-soft">Your route</span><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">The journey on the map</h2><p className="text-sm text-on-shell-muted mt-2">A lightweight static map shows the sequence of the journey without loading an interactive mapping library.</p></div><TourRouteMap tour={tour} /></section>
      <section id="inclusions" className={`${sectionOffsetClass} grid sm:grid-cols-2 gap-5`}>{includedItems.length ? <div className="min-w-0 rounded-2xl bg-emerald-50 border border-emerald-200 p-5 sm:p-6"><h2 className="font-serif-luxury text-xl font-bold text-action-strong">What Is Included</h2><ul className="mt-4 space-y-2.5">{includedItems.map((item, index) => <li key={index} className="flex gap-2 text-sm text-action"><Check className="w-4 h-4 mt-0.5 shrink-0" /><span>{item}</span></li>)}</ul></div> : null}{excludedItems.length ? <div className="min-w-0 rounded-2xl bg-rose-50 border border-rose-200 p-5 sm:p-6"><h2 className="font-serif-luxury text-xl font-bold text-rose-900">What Is Excluded</h2><ul className="mt-4 space-y-2.5">{excludedItems.map((item, index) => <li key={index} className="flex gap-2 text-sm text-rose-900"><X className="w-4 h-4 mt-0.5 shrink-0" /><span>{item}</span></li>)}</ul></div> : null}</section>
      <section id="pricing" className={sectionOffsetClass}><DynamicPricingTable tour={tour} /></section>
      <section id="faqs" className={`${sectionOffsetClass} rounded-2xl bg-white border border-border-strong p-5 sm:p-7 text-ink`}><h2 className="font-serif-luxury text-2xl font-bold text-ink-strong">Safari essentials</h2><div className="mt-5 grid md:grid-cols-2 gap-5">{tour.childrenPolicy ? <div><h3 className="text-sm font-bold text-ink-strong">Children policy</h3><p className="text-sm text-ink-muted mt-1">{tour.childrenPolicy}</p></div> : null}{tour.startingDates ? <div><h3 className="text-sm font-bold text-ink-strong">Starting dates</h3><p className="text-sm text-ink-muted mt-1">{tour.startingDates}</p></div> : null}<div><h3 className="text-sm font-bold text-ink-strong">Availability</h3><p className="text-sm text-ink-muted mt-1">{tour.bookingAvailability || 'On request'}</p></div><div><h3 className="text-sm font-bold text-ink-strong">Route</h3><p className="text-sm text-ink-muted mt-1">{tour.startingLocation} → {tour.destinations?.join(' → ')} → {tour.endingLocation}</p></div></div>{tour.importantInformation?.length ? <div className="mt-6 pt-5 border-t border-border"><h3 className="text-sm font-bold text-ink-strong">Important information</h3><ul className="list-clean mt-3">{tour.importantInformation.map(info => <li key={info}>{info}</li>)}</ul></div> : null}</section>
      <section className="rounded-[2rem] border border-brand-deep bg-shell p-7 sm:p-10 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Make it yours</span><h2 className="font-serif-luxury text-3xl font-bold text-white mt-2">Want this route adjusted around your dates?</h2><p className="text-sm text-on-shell-muted mt-2 max-w-2xl">Share your group, dates and priorities. We can adapt nights, stays and pacing before you decide to proceed.</p></div><div className="flex flex-col sm:flex-row gap-3"><EnquiryButton label="Request this safari" tourTitle={tour.title} className="min-h-12 px-6 rounded-xl bg-brand-soft hover:bg-brand-soft text-ink-strong font-extrabold text-sm" /><a href={`https://wa.me/254729000410?text=${encodeURIComponent(`Hello Good Secrets Safaris, I'd like to ask about ${tour.title}.`)}`} target="_blank" rel="noopener noreferrer" className="min-h-12 px-6 rounded-xl border border-white/20 text-white font-bold text-sm inline-flex items-center justify-center gap-2"><MessageCircle className="w-4 h-4" />WhatsApp</a></div></section>
    </main>
    <div className="max-w-7xl mx-auto px-4 sm:px-8 pb-16">
      <RelatedPlanningGuides guides={planningGuides} eyebrow="Research this safari" title="Questions worth answering before you book" />
    </div>
  </div>;
}
