import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { EnquiryButton } from '../../../components/EnquiryButton';
import { ShortlistButton } from '../../../components/ShortlistButton';
import { getTourBySlug, getTours } from '../../../lib/api';
import { siteUrl } from '../../../lib/site';

export const revalidate = 900;
export const dynamicParams = true;
export async function generateStaticParams(){return (await getTours()).map((tour)=>({slug:tour.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const tour=await getTourBySlug(slug);if(!tour)return{};return{title:tour.seo?.title||tour.title,description:tour.seo?.description||tour.shortDescription,alternates:{canonical:`/safaris/${tour.slug}`},openGraph:{title:tour.title,description:tour.shortDescription,url:`/safaris/${tour.slug}`,images:[tour.images?.[0]||'/images/catalog/mara-savannah.jpg']}};}

function DecisionSummary({tour}:{tour:Awaited<ReturnType<typeof getTourBySlug>> extends infer T?NonNullable<T>:never}){const facts=[['Best for',tour.travelerTypes?.join(', ')],['Safari style',tour.travelStyles?.join(', ')],['Comfort',tour.comfortLevel],['Duration',tour.durationLabel],['Route',tour.destinations?.join(' → ')],['Starts / ends',[tour.startingLocation,tour.endingLocation].filter(Boolean).join(' → ')]].filter(([,value])=>Boolean(value));return <section className="section compact"><div className="container"><div className="section-header"><div><p className="eyebrow">Decision support</p><h2>Is this safari right for you?</h2><p>These facts come from the published safari information and can be adjusted when you request a quote.</p></div></div><div className="facts">{facts.map(([label,value])=><div className="fact" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>}

export default async function SafariDetailPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const tour=await getTourBySlug(slug);if(!tour)notFound();
  const url=siteUrl(`/safaris/${tour.slug}`);const image=tour.images?.[0]||'/images/catalog/mara-savannah.jpg';
  const schema=[{'@context':'https://schema.org','@type':'TouristTrip',name:tour.title,description:tour.fullDescription||tour.shortDescription,image:siteUrl(image),url,itinerary:tour.itinerary?.map((day)=>({'@type':'TouristAttraction',name:`Day ${day.day}: ${day.title}`,description:day.description}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl('/')},{'@type':'ListItem',position:2,name:'Safaris',item:siteUrl('/safaris')},{'@type':'ListItem',position:3,name:tour.title,item:url}]}];
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <section className="detail-hero"><div className="container detail-grid"><div className="detail-copy"><p className="eyebrow">{tour.country} · {tour.durationLabel}</p><h1>{tour.title}</h1><p>{tour.shortDescription}</p><div className="chips">{tour.travelStyles?.slice(0,5).map((style)=><span className="chip" key={style}>{style}</span>)}</div><p><strong>From {tour.currency==='KES'?'KES ':'$'}{Number(tour.priceFrom||0).toLocaleString()}</strong> per person guide price</p><div className="hero-actions"><EnquiryButton label="Request this safari" tourTitle={tour.title}/><ShortlistButton safari={{id:tour.id,title:tour.title,slug:tour.slug,image,durationLabel:tour.durationLabel,country:tour.country,priceFrom:tour.priceFrom}}/></div></div><div className="detail-media"><Image src={image} alt={tour.title} fill priority sizes="(max-width:1050px) 100vw,50vw"/></div></div></section>
    <DecisionSummary tour={tour}/>
    <section className="section"><div className="container content-layout"><div><div className="prose-card"><section><h2>Safari overview</h2><p>{tour.fullDescription||tour.shortDescription}</p></section>{tour.accommodationSummary?<section><h2>Accommodation</h2><p>{tour.accommodationSummary}</p></section>:null}{tour.mealsSummary?<section><h2>Meals</h2><p>{tour.mealsSummary}</p></section>:null}</div>{tour.itinerary?.length?<section style={{marginTop:28}}><div className="section-header"><div><p className="eyebrow">Day by day</p><h2>Safari itinerary</h2></div></div><div className="timeline">{tour.itinerary.map((day)=><article className="timeline-item" key={`${day.day}-${day.title}`}><div className="timeline-day">{day.day}</div><div><h3>{day.title}</h3>{day.subtitle?<strong>{day.subtitle}</strong>:null}<p>{day.description}</p>{day.accommodation?<p><strong>Stay:</strong> {day.accommodation}</p>:null}{day.meals?<p><strong>Meals:</strong> {day.meals}</p>:null}</div></article>)}</div></section>:null}<section className="grid-2" style={{marginTop:28}}><div className="prose-card"><h2>Included</h2><ul className="list-clean">{[...(tour.includedServices||[]),...(tour.includedActivities||[])].map((item)=><li key={item}>{item}</li>)}</ul></div><div className="prose-card"><h2>Not included</h2><ul>{tour.exclusions?.map((item)=><li key={item}>{item}</li>)}</ul></div></section>{tour.importantInformation?.length?<div className="prose-card" style={{marginTop:28}}><h2>Important information</h2><ul>{tour.importantInformation.map((item)=><li key={item}>{item}</li>)}</ul></div>:null}</div><aside className="sticky-card"><p className="eyebrow">Plan this itinerary</p><h3>{tour.title}</h3><p>{tour.durationLabel} · {tour.comfortLevel}</p><p><strong>Starts:</strong> {tour.startingLocation}<br/><strong>Ends:</strong> {tour.endingLocation}</p><p><strong>Availability:</strong> {tour.bookingAvailability||'On request'}</p><EnquiryButton label="Request a quote" tourTitle={tour.title}/><Link className="button secondary" href="/guides/kenya-safari-cost-guide">Understand safari pricing</Link></aside></div></section>
  </>;
}
