import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { EnquiryButton } from '../../../components/EnquiryButton';
import { getHotelBySlug, getHotels } from '../../../lib/api';
import { siteUrl } from '../../../lib/site';

export const revalidate=900;export const dynamicParams=true;
export async function generateStaticParams(){return (await getHotels()).map((hotel)=>({slug:hotel.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const hotel=await getHotelBySlug(slug);if(!hotel)return{};return{title:hotel.seo?.title||hotel.name,description:hotel.seo?.description||hotel.description,alternates:{canonical:`/hotels/${hotel.slug}`},openGraph:{title:hotel.name,description:hotel.description,url:`/hotels/${hotel.slug}`,images:[hotel.images?.[0]||'/images/catalog/picnic-lunch-in-the-wild.jpg']}};}

export default async function HotelDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const hotel=await getHotelBySlug(slug);if(!hotel)notFound();const image=hotel.images?.[0]||'/images/catalog/picnic-lunch-in-the-wild.jpg';const url=siteUrl(`/hotels/${hotel.slug}`);const schema=[{'@context':'https://schema.org','@type':'LodgingBusiness',name:hotel.name,description:hotel.description,image:hotel.images?.map((src)=>siteUrl(src)),url,address:{'@type':'PostalAddress',addressLocality:hotel.location,addressCountry:hotel.country}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl('/')},{'@type':'ListItem',position:2,name:'Hotels',item:siteUrl('/hotels')},{'@type':'ListItem',position:3,name:hotel.name,item:url}]}];return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="detail-hero"><div className="container detail-grid"><div className="detail-copy"><p className="eyebrow">{hotel.category} · {hotel.location}</p><h1>{hotel.name}</h1><p>{hotel.description}</p><div className="chips"><span className="chip">{hotel.country}</span>{hotel.isFamilyFriendly?<span className="chip">Family friendly</span>:null}{hotel.isHoneymoonFriendly?<span className="chip">Honeymoon friendly</span>:null}{hotel.isSeniorFriendly?<span className="chip">Comfort focused</span>:null}</div><p><strong>From ${Number(hotel.priceFromUSD||0).toLocaleString()}</strong> guide price</p><EnquiryButton label="Ask about this stay" hotelTitle={hotel.name}/></div><div className="detail-media"><Image src={image} alt={hotel.name} fill priority sizes="(max-width:1050px) 100vw,50vw"/></div></div></section><section className="section"><div className="container content-layout"><div><div className="grid-2"><div className="prose-card"><h2>Facilities</h2><ul className="list-clean">{hotel.facilities?.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="prose-card"><h2>Room types</h2><ul className="list-clean">{hotel.roomTypes?.map((item)=><li key={item}>{item}</li>)}</ul></div></div><div className="grid-2" style={{marginTop:22}}><div className="prose-card"><h2>Included</h2><ul className="list-clean">{hotel.inclusions?.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="prose-card"><h2>Not included</h2><ul>{hotel.exclusions?.map((item)=><li key={item}>{item}</li>)}</ul></div></div></div><aside className="sticky-card"><p className="eyebrow">Use it in an itinerary</p><h3>{hotel.name}</h3><p>Availability, room category and final price should be reconfirmed for your exact travel dates.</p><EnquiryButton label="Include this in my safari" hotelTitle={hotel.name}/></aside></div></section></>}
