import React from 'react';
import { Destination, Tour, Hotel } from '../types';
import { useData } from '../context/DataContext';
import { PageMeta } from '../components/common/PageMeta';
import { TourCard } from '../components/tours/TourCard';
import { HotelCard } from '../components/hotels/HotelCard';
import { destinationImage } from '../lib/destinationImage';
import { Calendar, ArrowLeft, Sparkles, ChevronRight, CheckCircle2, Compass, MessageCircle, ShieldCheck } from 'lucide-react';

interface DestinationDetailViewProps { destination: Destination; onBack: () => void; onSelectTour: (tour: Tour) => void; onSelectHotel: (hotel: Hotel) => void; onOpenEnquiryModal: (payload?: any) => void; }

export const DestinationDetailView: React.FC<DestinationDetailViewProps> = ({ destination, onBack, onSelectTour, onSelectHotel, onOpenEnquiryModal }) => {
  const { tours, hotels, getWhatsAppUrl } = useData();
  const matchingTours = tours.filter(t => t.destinations.some(d => d.toLowerCase().includes(destination.name.toLowerCase())) || t.title.toLowerCase().includes(destination.name.toLowerCase()) || t.destinations.some(d => destination.name.toLowerCase().includes(d.toLowerCase())));
  const matchingHotels = hotels.filter(h => h.location.toLowerCase().includes(destination.name.toLowerCase()) || destination.name.toLowerCase().includes(h.location.toLowerCase()) || h.country.toLowerCase() === destination.country.toLowerCase());
  const whatsappUrl = getWhatsAppUrl({});
  const image = destinationImage(destination);
  const openDestinationEnquiry = () => onOpenEnquiryModal({ initialType: `Safari to ${destination.name}`, initialDestination: destination.name, contextItems: [`Destination: ${destination.name}, ${destination.country}`] });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-8 py-8 space-y-14">
      <PageMeta title={`${destination.name} Safari Guide`} description={destination.description || destination.subtitle} image={image} canonicalPath={`/destinations/${destination.slug}`} structuredData={[{ '@context':'https://schema.org','@type':'TouristDestination',name:destination.name,description:destination.description || destination.subtitle,image,address:{ '@type':'PostalAddress',addressCountry:destination.country } },{ '@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{ '@type':'ListItem',position:1,name:'Destinations',item:'https://www.goodsecretssafaris.com/destinations' },{ '@type':'ListItem',position:2,name:destination.name,item:`https://www.goodsecretssafaris.com/destinations/${destination.slug}` }] }]} />

      <div className="flex items-center justify-between text-xs text-[#c7d2cb]"><button onClick={onBack} className="min-h-11 inline-flex items-center gap-1.5 hover:text-[#e6bc65] transition-colors font-semibold"><ArrowLeft className="w-4 h-4" /><span>All destinations</span></button><div className="hidden sm:flex items-center gap-2" aria-label="Breadcrumb"><span>{destination.country}</span><ChevronRight className="w-3 h-3 text-[#8f9d94]" /><span className="text-white font-medium">{destination.name}</span></div></div>

      <section className="relative rounded-[2rem] overflow-hidden min-h-[460px] sm:min-h-[560px] flex flex-col justify-end p-6 sm:p-12 border border-white/10 shadow-xl"><img src={image} alt={`${destination.name}, ${destination.country}`} referrerPolicy="no-referrer" className="absolute inset-0 w-full h-full object-cover -z-10" /><div className="absolute inset-0 bg-gradient-to-t from-black/95 via-black/50 to-black/20 -z-10" /><div className="space-y-4 max-w-3xl"><span className="inline-flex px-3 py-1.5 rounded-full text-xs font-bold bg-[#8a611d] text-white">{destination.country}</span><h1 className="font-serif-luxury text-4xl sm:text-6xl font-bold text-white leading-tight">{destination.name} safari guide</h1><p className="text-base sm:text-lg text-white leading-relaxed font-medium max-w-2xl">{destination.subtitle}</p><div className="pt-2 flex flex-col sm:flex-row gap-3"><button onClick={openDestinationEnquiry} className="min-h-12 px-6 rounded-xl bg-[#e6bc65] hover:bg-[#f0ca79] text-[#161f19] font-extrabold text-sm transition-all shadow-md inline-flex items-center justify-center gap-2"><Sparkles className="w-4 h-4" />Plan a {destination.name} safari</button><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="min-h-12 px-5 rounded-xl border border-white/25 bg-black/20 text-white font-bold text-sm inline-flex items-center justify-center gap-2"><MessageCircle className="w-4 h-4" />Ask a local expert</a></div></div></section>

      <section className="grid lg:grid-cols-12 gap-8 lg:gap-12 items-start">
        <div className="lg:col-span-8 space-y-8"><article className="p-7 sm:p-9 rounded-3xl bg-white border border-[#ded8cb] space-y-5 shadow-sm"><span className="text-xs font-extrabold uppercase tracking-wider text-[#76541a]">Why go</span><h2 className="font-serif-luxury text-3xl font-bold text-[#161f19]">Why visit {destination.name}?</h2><p className="text-base text-[#46544b] leading-relaxed whitespace-pre-line">{destination.description}</p>{(destination.wildlife?.length ?? 0) > 0 && <div className="pt-4 border-t border-[#e7e1d5]"><h3 className="text-xs font-extrabold uppercase tracking-wider text-[#76541a] mb-3">Wildlife & highlights</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{destination.wildlife.map((h, i) => <div key={i} className="flex items-start gap-2 text-sm text-[#303e35]"><CheckCircle2 className="w-4 h-4 text-[#76541a] shrink-0 mt-0.5" /><span>{h}</span></div>)}</div></div>}</article>
          <article className="rounded-3xl border border-white/10 bg-white/5 p-7 sm:p-9"><span className="text-xs font-bold uppercase tracking-widest text-[#e6bc65]">Build it into a real itinerary</span><h2 className="font-serif-luxury text-3xl font-bold text-white mt-2">The destination is only one part of the route.</h2><p className="text-base text-[#c7d2cb] mt-3 leading-relaxed">Drive times, park-entry timing, lodge location and the order of destinations can change how relaxed or rushed a safari feels. Use the itineraries below as starting points, then ask us whether {destination.name} makes sense for your dates and priorities.</p><div className="mt-6 grid sm:grid-cols-3 gap-3">{[['Wildlife priority','Tell us what you most hope to see.'],['Pace','Decide whether you prefer more ground covered or more time in each place.'],['Stay style','Compare lodge location and comfort, not only the room photographs.']].map(([title,desc]) => <div key={title} className="border-t border-white/15 pt-4"><strong className="text-white text-sm">{title}</strong><p className="text-xs text-[#aebbb2] mt-1 leading-relaxed">{desc}</p></div>)}</div></article></div>
        <aside className="lg:col-span-4 space-y-4"><div className="p-6 rounded-3xl bg-white border border-[#ded8cb] space-y-4 shadow-sm"><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-[#76541a]"><Calendar className="w-4 h-4" /><span>Best time to visit</span></div><p className="text-base font-bold text-[#161f19]">{destination.bestTimeToVisit}</p><p className="text-sm text-[#526158]">Season is only one input. Your wildlife priorities, budget and wider route can change the best travel window for you.</p><div className="pt-3 border-t border-[#e7e1d5]"><span className="text-xs font-extrabold uppercase tracking-wider text-[#536158] block mb-2">Look out for</span><div className="flex flex-wrap gap-2">{destination.wildlife.map((w, i) => <span key={i} className="px-2.5 py-1.5 rounded-lg bg-[#faf8f2] text-xs font-semibold text-[#303e35] border border-[#d7d1c4]">{w}</span>)}</div></div></div><div className="p-6 rounded-3xl bg-[#152019] border border-white/10 space-y-3 shadow-sm"><ShieldCheck className="w-5 h-5 text-[#e6bc65]" /><h2 className="font-serif-luxury text-xl font-bold text-white">Not sure how many nights?</h2><p className="text-sm text-[#c7d2cb] leading-relaxed">Tell us the rest of your route. We can help balance game-drive time against transfers and the number of parks you want to include.</p><button onClick={openDestinationEnquiry} className="w-full min-h-11 rounded-xl bg-[#8a611d] hover:bg-[#704d15] text-white text-sm font-bold">Ask a safari expert</button></div></aside>
      </section>

      <section className="space-y-6 pt-2"><div><span className="text-xs font-bold uppercase tracking-widest text-[#e6bc65]">Safari ideas</span><h2 className="font-serif-luxury text-2xl sm:text-4xl font-bold text-white mt-1">Journeys featuring {destination.name}</h2><p className="text-sm text-[#c7d2cb] mt-1">Use these as starting points — each can be adjusted to your dates and interests.</p></div>{matchingTours.length > 0 ? <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{matchingTours.map(tour => <TourCard key={tour.id} tour={tour} onSelect={onSelectTour} onEnquire={onOpenEnquiryModal} />)}</div> : <div className="p-7 rounded-2xl bg-white border border-[#ded8cb] text-center"><p className="text-sm text-[#46544b]">We can create a custom itinerary including {destination.name}.</p><button onClick={openDestinationEnquiry} className="mt-4 min-h-11 px-5 rounded-xl bg-[#8a611d] hover:bg-[#704d15] text-white text-sm font-bold">Request a custom route</button></div>}</section>
      {matchingHotels.length > 0 && <section className="space-y-6 pt-2"><div><span className="text-xs font-bold uppercase tracking-widest text-[#e6bc65]">Places to stay</span><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">Stays to compare around {destination.name}</h2><p className="text-sm text-[#c7d2cb] mt-2">Use accommodation as part of route planning: location, transfer time and the kind of experience matter as much as room style.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{matchingHotels.slice(0, 4).map(hotel => <HotelCard key={hotel.id} hotel={hotel} onSelect={onSelectHotel} onEnquire={onOpenEnquiryModal} />)}</div></section>}
      <section className="rounded-[2rem] bg-[#17231b] border border-[#5f512f] p-7 sm:p-10 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6"><div><span className="text-xs font-bold uppercase tracking-widest text-[#e6bc65]">Your route, not a template</span><h2 className="font-serif-luxury text-3xl font-bold text-white mt-2">Want {destination.name} without building the whole trip yourself?</h2><p className="text-sm text-[#d7dfda] mt-2 max-w-2xl">Share your dates, travel style and the other places on your wish list. We can suggest how this destination fits into a private East Africa journey.</p></div><button onClick={openDestinationEnquiry} className="min-h-12 shrink-0 px-6 rounded-xl bg-[#e6bc65] hover:bg-[#f0ca79] text-[#161f19] font-extrabold text-sm inline-flex items-center gap-2"><Compass className="w-4 h-4" />Plan my route</button></section>
    </div>
  );
};
