import React from 'react';
import { PageMeta } from '../components/common/PageMeta';
import { SCHEMA_CONTEXT } from '../lib/site';
import { ArrowRight, CheckCircle2, Compass, MessageCircle, ShieldCheck, Users, WalletCards } from 'lucide-react';

interface DirectBookingViewProps { onOpenEnquiryModal: (payload?: any) => void; }

const comparisonRows = [
  ['Who plans the trip?', 'You communicate directly with the local safari team shaping the route.', 'A marketplace or overseas agent may sit between you and the operator.'],
  ['How flexible is the itinerary?', 'Dates, pace, nights and accommodation can be discussed around your group.', 'Some products are presented as fixed packages or standardized departures.'],
  ['Where do questions go?', 'You have direct email, phone and WhatsApp channels to Good Secrets Safaris.', 'Questions may pass through an intermediary before reaching the local operator.'],
  ['When do you commit?', 'An enquiry is only a planning request. Trip and payment terms are reviewed before you choose to proceed.', 'Processes vary by marketplace or agency.']
];

export const DirectBookingView: React.FC<DirectBookingViewProps> = ({ onOpenEnquiryModal }) => (
  <div className="pb-20">
    <PageMeta
      title="Booking a Safari Directly with a Local Kenya Operator"
      description="Understand how direct safari planning works with Good Secrets Safaris, what happens after an enquiry, what to check before paying, and how private trips differ from marketplace packages."
      canonicalPath="/book-direct"
      structuredData={{
        '@context': SCHEMA_CONTEXT,
        '@type': 'FAQPage',
        mainEntity: [
          { '@type': 'Question', name: 'Does submitting a safari enquiry create a booking?', acceptedAnswer: { '@type': 'Answer', text: 'No. Submitting an enquiry to Good Secrets Safaris is a planning request and does not by itself confirm a booking or take payment.' } },
          { '@type': 'Question', name: 'Can a private East Africa safari be customized?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Routes, dates, pacing, accommodation and experiences can be discussed around the traveler’s priorities and availability.' } },
          { '@type': 'Question', name: 'What should I review before confirming a safari?', acceptedAnswer: { '@type': 'Answer', text: 'Review the itinerary, inclusions, exclusions, accommodation, pricing, payment terms and cancellation terms before choosing whether to proceed.' } }
        ]
      }}
    />

    <header className="relative overflow-hidden border-b border-white/10">
      <img src="/images/catalog/picnic-lunch-in-the-wild.jpg" alt="Private safari picnic in East Africa" fetchPriority="high" className="absolute inset-0 w-full h-full object-cover" />
      <div className="absolute inset-0 bg-gradient-to-r from-shell/95 via-shell/80 to-black/45" />
      <div className="relative max-w-7xl mx-auto px-4 sm:px-8 py-20 sm:py-28">
        <div className="max-w-3xl space-y-5"><span className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.18em] text-brand-soft"><Compass className="w-4 h-4" />Plan direct with East Africa</span><h1 className="font-serif-luxury text-4xl sm:text-6xl font-bold text-white leading-[1.06]">Booking direct should feel more personal — not more risky.</h1><p className="text-base sm:text-xl text-white/90 leading-relaxed">If you are comparing SafariBookings, an overseas travel advisor and a local operator, the real question is not simply price. It is whether you understand who is responsible for your trip, what is included and what happens after you enquire.</p><button onClick={() => onOpenEnquiryModal({ initialType: 'Direct safari planning' })} className="min-h-12 px-7 rounded-xl bg-brand-soft hover:bg-brand-soft text-ink-strong font-extrabold text-sm shadow-lg">Talk directly with our safari team</button></div>
      </div>
    </header>

    <main className="max-w-7xl mx-auto px-4 sm:px-8 py-14 sm:py-20 space-y-20">
      <section className="grid lg:grid-cols-12 gap-10 items-start"><div className="lg:col-span-5 space-y-4"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">What direct planning means</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white">One relationship from first idea to safari.</h2><p className="text-base text-on-shell-muted leading-relaxed">Good Secrets Safaris is not trying to replace the value of independent review platforms. SafariBookings and Tripadvisor are useful places to verify other travelers’ experiences. The difference is that once you are ready to plan, you can communicate directly with the team organizing the journey.</p><a href="/reviews" className="inline-flex items-center gap-2 min-h-11 text-brand-soft font-bold text-sm hover:text-white">See independent traveler reviews <ArrowRight className="w-4 h-4" /></a></div><div className="lg:col-span-7 rounded-3xl bg-white border border-border-strong p-6 sm:p-8 text-ink-strong"><div className="grid sm:grid-cols-2 gap-5">{[['Private itinerary','Adjust nights, route and pace around your group.'],['Direct communication','Email, phone and WhatsApp channels to the local team.'],['Clear proposal','Review what is included and excluded before proceeding.'],['Local trip support','Contact the East Africa-based team while you travel.']].map(([title,desc]) => <div key={title} className="flex gap-3"><CheckCircle2 className="w-5 h-5 text-action shrink-0 mt-0.5" /><div><h3 className="font-bold">{title}</h3><p className="text-sm text-ink-muted mt-1">{desc}</p></div></div>)}</div></div></section>

      <section className="space-y-8"><div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Marketplace vs direct</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white mt-2">Use marketplaces to research. Use direct conversation to personalize.</h2><p className="text-base text-on-shell-muted mt-3">This comparison is about the planning relationship, not a claim that one channel is always cheaper or better.</p></div><div className="overflow-x-auto rounded-3xl border border-border-strong bg-white"><table className="min-w-[760px] w-full text-left text-sm text-ink"><thead className="bg-surface-muted"><tr><th className="p-4 font-extrabold text-ink-strong">Question</th><th className="p-4 font-extrabold text-action">Planning direct with Good Secrets</th><th className="p-4 font-extrabold text-ink-strong">Marketplace / intermediary</th></tr></thead><tbody>{comparisonRows.map(([q,direct,market]) => <tr key={q} className="border-t border-border"><th className="p-4 align-top font-bold text-ink-strong">{q}</th><td className="p-4 align-top">{direct}</td><td className="p-4 align-top text-ink-muted">{market}</td></tr>)}</tbody></table></div></section>

      <section className="rounded-[2rem] bg-page border border-border-strong p-7 sm:p-10 lg:p-12 text-ink-strong"><div className="max-w-3xl"><span className="text-xs font-extrabold uppercase tracking-widest text-brand-deep">Before you pay anyone</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold mt-2">A practical safari buyer checklist.</h2><p className="text-base text-ink-muted mt-3">Whether booking locally or through an overseas company, a high-value trip deserves careful verification.</p></div><div className="grid md:grid-cols-2 gap-x-8 gap-y-5 mt-8">{['Read independent reviews on third-party platforms.','Confirm the company contact details you are using are genuine.','Review the exact itinerary, accommodation and transport arrangements.','Understand what the quoted price includes and excludes.','Read the payment schedule and cancellation terms before sending money.','Ask who to contact if plans change while you are in East Africa.','Check passport, visa, insurance and health requirements using official sources.','Keep copies of your confirmed itinerary, receipts and emergency contacts.'].map(item => <div key={item} className="flex gap-3"><ShieldCheck className="w-5 h-5 text-brand-deep shrink-0 mt-0.5" /><span className="text-sm leading-relaxed">{item}</span></div>)}</div></section>

      <section className="grid md:grid-cols-3 gap-5"><article className="rounded-3xl border border-white/10 bg-white/5 p-7"><Users className="w-7 h-7 text-brand-soft" /><h3 className="font-serif-luxury text-xl font-bold text-white mt-4">Private vs group safari</h3><p className="text-sm text-on-shell-muted mt-2 leading-relaxed">Private safaris offer more control over pace, game-drive timing and daily decisions. Group tours can be a good fit when fixed schedules and shared costs matter more.</p></article><article className="rounded-3xl border border-white/10 bg-white/5 p-7"><WalletCards className="w-7 h-7 text-brand-soft" /><h3 className="font-serif-luxury text-xl font-bold text-white mt-4">Budget without guesswork</h3><p className="text-sm text-on-shell-muted mt-2 leading-relaxed">Treat online prices as planning guides until dates, accommodation and group size are confirmed. Safari rates can change significantly by season and lodge choice.</p></article><article className="rounded-3xl border border-white/10 bg-white/5 p-7"><MessageCircle className="w-7 h-7 text-brand-soft" /><h3 className="font-serif-luxury text-xl font-bold text-white mt-4">Ask uncomfortable questions</h3><p className="text-sm text-on-shell-muted mt-2 leading-relaxed">A professional planner should be comfortable explaining transfers, long drive days, park fees, accommodation trade-offs and what happens if plans change.</p></article></section>

      <section className="rounded-[2rem] overflow-hidden grid lg:grid-cols-2 border border-white/10 bg-shell"><div className="min-h-80"><img src="/images/catalog/family-safari-game-drive.jpg" alt="Travelers on a private safari game drive" loading="lazy" className="w-full h-full object-cover" /></div><div className="p-8 sm:p-10 flex flex-col justify-center"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Ready to compare a real itinerary?</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white mt-2">Start with a conversation, not a checkout.</h2><p className="text-base text-on-shell-muted mt-4 leading-relaxed">Tell us your dates, group size and the kind of trip you have in mind. We can suggest a route and explain the trade-offs before you decide whether Good Secrets is the right fit.</p><div className="mt-6 flex flex-col sm:flex-row gap-3"><button onClick={() => onOpenEnquiryModal({ initialType: 'Direct safari planning' })} className="min-h-12 px-6 rounded-xl bg-brand-soft hover:bg-brand-soft text-ink-strong font-extrabold text-sm">Request a safari plan</button><a href="/safaris" className="min-h-12 px-6 rounded-xl border border-white/20 text-white font-bold text-sm inline-flex items-center justify-center">Browse safari ideas</a></div></div></section>
    </main>
  </div>
);
