import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { Tour } from '../types';
import { useData } from '../context/DataContext';
import { useShortlist } from '../context/ShortlistContext';
import { PageMeta } from '../components/common/PageMeta';
import { ItineraryTimeline } from '../components/itinerary/ItineraryTimeline';
import { DynamicPricingTable } from '../components/pricing/DynamicPricingTable';
import { TourRouteMap } from '../components/tours/TourRouteMap';
import { ArrowLeft, CalendarDays, Camera, Check, CircleHelp, Clock, Compass, Heart, Map, MapPin, MessageCircle, ShieldCheck, Sparkles, Star, X } from 'lucide-react';

interface TourDetailViewProps { tour: Tour; onBack: () => void; onOpenEnquiryModal: (payload?: any) => void; onSelectDestination?: (destName: string) => void; }
const sectionLinks = [{ id: 'overview', label: 'Overview', Icon: Compass }, { id: 'itinerary', label: 'Itinerary', Icon: CalendarDays }, { id: 'route', label: 'Route', Icon: Map }, { id: 'inclusions', label: 'Inclusions', Icon: Check }, { id: 'gallery', label: 'Gallery', Icon: Camera }, { id: 'pricing', label: 'Pricing', Icon: Sparkles }, { id: 'faqs', label: 'FAQs', Icon: CircleHelp }];

export const TourDetailView: React.FC<TourDetailViewProps> = ({ tour, onBack, onOpenEnquiryModal }) => {
  const { formatPrice, getWhatsAppUrl, isKenyanResidentMode } = useData();
  const { isTourSaved, toggleTour } = useShortlist();
  const isSaved = isTourSaved(tour.slug);
  const [activeImageIdx, setActiveImageIdx] = useState(0);
  const price = formatPrice(tour.sharingPrice || tour.priceFrom);
  const whatsappUrl = getWhatsAppUrl({ tourTitle: tour.title });
  const includedItems = [...(tour.includedServices ?? []), ...(tour.includedActivities ?? [])];
  const excludedItems = tour.exclusions ?? [];
  const goTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  const sectionOffsetClass = 'scroll-mt-44 sm:scroll-mt-52';

  return <div className="pb-28 lg:pb-12">
    <PageMeta title={tour.title} description={tour.shortDescription} image={tour.images?.[0]} canonicalPath={`/safaris/${tour.slug}`} structuredData={[{ '@context':'https://schema.org','@type':'TouristTrip',name:tour.title,description:tour.shortDescription,touristType:tour.travelStyles, itinerary: tour.destinations?.join(' → ') },{ '@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{ '@type':'ListItem',position:1,name:'Safaris',item:'https://www.goodsecretssafaris.com/safaris' },{ '@type':'ListItem',position:2,name:tour.title,item:`https://www.goodsecretssafaris.com/safaris/${tour.slug}` }] }]} />
    <section className="relative min-h-[440px] sm:min-h-[520px] lg:min-h-[570px] overflow-hidden bg-[#0c120e]"><img src={tour.images?.[0]} alt={`${tour.title} safari`} fetchPriority="high" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#07100a]/95 via-[#07100a]/35 to-black/25" /><div className="relative max-w-7xl mx-auto px-4 sm:px-8 pt-6 pb-10 min-h-[440px] sm:min-h-[520px] lg:min-h-[570px] flex flex-col justify-between"><div className="flex items-center justify-between gap-3"><button type="button" onClick={onBack} className="min-h-11 inline-flex items-center gap-2 rounded-full bg-black/45 px-4 text-sm font-semibold text-white backdrop-blur-sm border border-white/20 hover:bg-black/60"><ArrowLeft className="w-4 h-4" />All safaris</button><button type="button" onClick={() => toggleTour(tour.slug)} aria-pressed={isSaved} className={`min-h-11 inline-flex items-center gap-2 rounded-full px-4 text-sm font-bold backdrop-blur-sm border transition-colors ${isSaved ? 'bg-[#fffdf8] text-[#8a611d] border-white' : 'bg-black/45 text-white border-white/20 hover:bg-black/60'}`}><Heart className={`w-4 h-4 ${isSaved ? 'fill-current' : ''}`} />{isSaved ? 'Saved' : 'Save'}</button></div><div className="max-w-3xl">{(tour.featured || tour.popular) && <span className="inline-flex rounded-full bg-[#1b4332] px-3 py-1.5 text-xs font-bold text-white shadow-sm mb-4">{tour.popular ? 'Popular Choice' : 'Featured Safari'}</span>}<h1 className="font-serif-luxury text-3xl sm:text-5xl lg:text-6xl font-bold text-white leading-[1.08] sm:leading-[1.05] break-words">{tour.title}</h1><div className="mt-5 flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-white/95"><span className="inline-flex items-center gap-1.5"><Clock className="w-4 h-4 text-[#e6bc65]" />{tour.durationLabel}</span><span className="inline-flex items-center gap-1.5"><MapPin className="w-4 h-4 text-[#e6bc65]" />{tour.country}</span></div></div></div></section>

    <div className="sticky top-[68px] sm:top-[112px] z-30 border-y border-[#ddd7ca] bg-[#fffdf8]/98 backdrop-blur-xl shadow-[0_6px_20px_rgba(15,23,18,0.10)]">
      <div className="max-w-7xl mx-auto px-2 sm:px-5 lg:px-6 flex items-center gap-2">
        <nav aria-label="Tour sections" className="min-w-0 flex-1 flex items-center overflow-x-auto scrollbar-hide py-1">
          {sectionLinks.map(({ id, label, Icon }) => <button type="button" key={id} onClick={() => goTo(id)} className="group shrink-0 min-h-12 px-3 sm:px-4 inline-flex items-center justify-center gap-2 rounded-lg text-xs sm:text-sm font-semibold text-[#405046] hover:text-[#76541a] hover:bg-[#f3eee3] transition-colors"><Icon className="w-[18px] h-[18px] shrink-0 text-[#526158] group-hover:text-[#76541a]" aria-hidden="true" /><span>{label}</span></button>)}
        </nav>
        <aside className="hidden xl:flex shrink-0 items-center gap-3 my-2 ml-2 rounded-xl border border-[#d8d1c3] bg-white px-3 py-2 shadow-sm">
          <div className="min-w-[106px] leading-tight"><span className="block text-[10px] font-bold uppercase tracking-wider text-[#76541a]">From</span><strong className="font-serif-luxury text-lg text-[#161f19]">{price}</strong><span className="block text-[10px] text-[#536158] mt-0.5">Per person sharing</span></div>
          <button type="button" onClick={() => onOpenEnquiryModal({ selectedTour: tour })} className="min-h-11 whitespace-nowrap rounded-xl bg-[#1b4332] hover:bg-[#123524] px-5 text-sm font-extrabold text-white shadow-sm">Request This Safari</button>
        </aside>
      </div>
    </div>

    <div className="relative z-10 bg-[#f8f5ed] border-b border-[#ded8cb]"><div className="max-w-7xl mx-auto px-4 sm:px-8 py-4 grid md:grid-cols-[1fr_auto] gap-4 md:items-center text-[#161f19]"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm"><span className="inline-flex items-center gap-2 font-bold"><span className="flex text-[#b77905]" aria-label="Independent traveler ratings"><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /><Star className="w-4 h-4 fill-current" /></span>Independent reviews</span><span className="text-[#536158]">SafariBookings + Tripadvisor</span><span className="inline-flex gap-1.5 items-center text-[#1b4332]"><ShieldCheck className="w-4 h-4" />No payment required to enquire</span></div><div className="flex gap-4"><a href="/reviews" className="text-sm font-bold text-[#76541a] hover:text-[#161f19]">Read reviews</a><a href="/plan-with-us" className="text-sm font-bold text-[#76541a] hover:text-[#161f19]">How we plan your safari</a></div></div></div>

    <main className="max-w-7xl mx-auto px-4 sm:px-8 py-8 sm:py-12 space-y-14">
      <section id="overview" className={`${sectionOffsetClass} grid lg:grid-cols-12 gap-8 lg:gap-12 items-start`}><div className="min-w-0 lg:col-span-5 space-y-5"><div><span className="text-xs font-bold uppercase tracking-wider text-[#e6bc65]">The experience</span><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">Safari overview</h2></div><p className="text-base text-[#c7d2cb] leading-relaxed whitespace-pre-line break-words">{tour.fullDescription || tour.shortDescription}</p><div className="grid grid-cols-2 gap-3 pt-2"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><Clock className="w-5 h-5 text-[#e6bc65] mb-2" /><span className="text-xs text-[#aebbb2] block">Duration</span><strong className="text-sm text-white">{tour.durationLabel}</strong></div><div className="rounded-xl border border-white/10 bg-white/5 p-3"><Compass className="w-5 h-5 text-[#e6bc65] mb-2" /><span className="text-xs text-[#aebbb2] block">Travel style</span><strong className="text-sm text-white">{tour.travelStyles?.[0] || 'Tailor-made'}</strong></div></div></div><div id="gallery" className={`min-w-0 ${sectionOffsetClass} lg:col-span-7 space-y-3`}><div className="aspect-[4/3] sm:aspect-[16/10] w-full rounded-2xl overflow-hidden relative bg-[#f4f2ec] border border-white/10"><img src={tour.images?.[activeImageIdx] || tour.images?.[0]} alt={`${tour.title} gallery image ${activeImageIdx + 1}`} loading="lazy" className="w-full h-full object-cover" /><span className="absolute bottom-3 right-3 rounded-full bg-black/70 px-3 py-1.5 text-xs font-semibold text-white">{activeImageIdx + 1} / {tour.images?.length || 1}</span></div>{tour.images?.length > 1 && <div className="flex gap-2 overflow-x-auto pb-1">{tour.images.map((img, idx) => <button type="button" key={img + idx} onClick={() => setActiveImageIdx(idx)} aria-pressed={activeImageIdx === idx} aria-label={`View photo ${idx + 1}`} className={`shrink-0 w-20 h-16 sm:w-28 sm:h-20 rounded-xl overflow-hidden border-2 ${activeImageIdx === idx ? 'border-[#e6bc65]' : 'border-transparent opacity-75'}`}><img src={img} alt="" loading="lazy" className="w-full h-full object-cover" /></button>)}</div>}</div></section>
      <section id="itinerary" className={sectionOffsetClass}><ItineraryTimeline itinerary={tour.itinerary} /></section>
      <section id="route" className={`${sectionOffsetClass} space-y-5`}><div><span className="text-xs font-bold uppercase tracking-wider text-[#e6bc65]">Your route</span><h2 className="font-serif-luxury text-2xl sm:text-3xl font-bold text-white mt-1">The journey on the map</h2><p className="text-sm text-[#c7d2cb] mt-2">A lightweight static map shows the sequence of the journey without loading an interactive mapping library.</p></div><TourRouteMap tour={tour} /></section>
      <section id="inclusions" className={`${sectionOffsetClass} grid sm:grid-cols-2 gap-5`}>{includedItems.length > 0 && <div className="min-w-0 rounded-2xl bg-emerald-50 border border-emerald-200 p-5 sm:p-6"><h2 className="font-serif-luxury text-xl font-bold text-[#163524]">What Is Included</h2><ul className="mt-4 space-y-2.5">{includedItems.map((item, idx) => <li key={idx} className="flex gap-2 text-sm text-[#254331]"><Check className="w-4 h-4 mt-0.5 shrink-0" /><span>{item}</span></li>)}</ul></div>}{excludedItems.length > 0 && <div className="min-w-0 rounded-2xl bg-rose-50 border border-rose-200 p-5 sm:p-6"><h2 className="font-serif-luxury text-xl font-bold text-rose-900">What Is Excluded</h2><ul className="mt-4 space-y-2.5">{excludedItems.map((item, idx) => <li key={idx} className="flex gap-2 text-sm text-rose-900"><X className="w-4 h-4 mt-0.5 shrink-0" /><span>{item}</span></li>)}</ul></div>}</section>
      <section id="pricing" className={sectionOffsetClass}><DynamicPricingTable tour={tour} /></section>
      <section id="faqs" className={`${sectionOffsetClass} rounded-2xl bg-white border border-[#ded8cb] p-5 sm:p-7`}><h2 className="font-serif-luxury text-2xl font-bold text-[#161f19]">Safari essentials</h2><div className="mt-5 grid md:grid-cols-2 gap-3 text-sm text-[#405046]"><div className="min-w-0 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] p-4"><strong className="block text-[#161f19] mb-1">What should I pack?</strong>Light neutral clothing, a warm layer for dawn drives, sun protection, binoculars and a soft-sided travel bag are practical starting points.</div><div className="min-w-0 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] p-4"><strong className="block text-[#161f19] mb-1">Can this itinerary change?</strong>Yes. This safari is a starting point and can be adapted around your dates, pace, interests and accommodation preferences.</div><div className="min-w-0 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] p-4"><strong className="block text-[#161f19] mb-1">Does requesting a quote book the safari?</strong>No. An enquiry starts the planning conversation. It does not take payment or confirm a booking.</div><div className="min-w-0 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] p-4"><strong className="block text-[#161f19] mb-1">When will I see payment and cancellation terms?</strong>Those terms should be reviewed with the final proposal before you choose whether to proceed.</div></div></section>
      <section className="hidden lg:grid grid-cols-3 gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-[#c7d2cb]"><span className="flex gap-2"><ShieldCheck className="w-5 h-5 text-[#e6bc65] shrink-0" />No payment required to enquire</span><span className="flex gap-2"><Sparkles className="w-5 h-5 text-[#e6bc65] shrink-0" />Tailor-made around your preferences</span><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="flex gap-2 hover:text-white"><MessageCircle className="w-5 h-5 text-[#e6bc65] shrink-0" />Ask about this safari on WhatsApp</a></section>
    </main>

    {createPortal(<div className="lg:hidden fixed inset-x-0 bottom-0 z-50 border-t border-[#d7d1c4] bg-[#fffdf8]/98 backdrop-blur-xl px-4 pt-3 pb-[max(12px,env(safe-area-inset-bottom))] shadow-[0_-8px_30px_rgba(0,0,0,0.16)]"><div className="max-w-lg mx-auto flex items-center gap-4"><div className="min-w-0 flex-1"><span className="block text-xs font-semibold text-[#76541a]">From</span><strong className="font-serif-luxury text-2xl leading-none text-[#161f19]">{price}</strong><span className="block text-[11px] text-[#536158] mt-1">Per person sharing</span></div><button type="button" onClick={() => onOpenEnquiryModal({ selectedTour: tour })} className="min-h-12 min-w-[150px] shrink-0 rounded-xl bg-[#1b4332] hover:bg-[#123524] px-5 text-sm font-extrabold text-white shadow-md">Request This Safari</button></div>{isKenyanResidentMode && tour.residentPriceKES && <p className="max-w-lg mx-auto mt-1 text-xs font-semibold text-[#1b4332]">Resident rate: KSH {tour.residentPriceKES.toLocaleString()}</p>}</div>, document.body)}
  </div>;
};
