import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { getBlogPostBySlug, getBlogPosts } from '../../../lib/api';
import { siteUrl } from '../../../lib/site';

export const revalidate=900;export const dynamicParams=true;
export async function generateStaticParams(){return (await getBlogPosts()).map((post)=>({slug:post.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const post=await getBlogPostBySlug(slug);if(!post)return{};return{title:post.title,description:post.excerpt,alternates:{canonical:`/blog/${post.slug}`},openGraph:{title:post.title,description:post.excerpt,type:'article',url:`/blog/${post.slug}`,images:[post.featuredImage]}};}

export default async function BlogDetailPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const post=await getBlogPostBySlug(slug);if(!post)notFound();const url=siteUrl(`/blog/${post.slug}`);const schema=[{'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.excerpt,image:siteUrl(post.featuredImage),author:{'@type':'Person',name:post.author?.name||'Good Secrets Safaris'},publisher:{'@type':'Organization',name:'Good Secrets Safaris'},datePublished:post.publishedDate,mainEntityOfPage:url},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:siteUrl('/')},{'@type':'ListItem',position:2,name:'Blog',item:siteUrl('/blog')},{'@type':'ListItem',position:3,name:post.title,item:url}]}];const blocks=post.content?.split(/\n{2,}/).filter(Boolean)||[];return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="page-hero"><div className="container guide-article"><p className="eyebrow">{post.category} · {post.readingTime}</p><h1>{post.title}</h1><p>{post.excerpt}</p><p>By {post.author?.name} · {post.publishedDate}</p></div></header><article className="section"><div className="container guide-article"><div className="hero-image"><Image src={post.featuredImage||'/images/catalog/mara-savannah.jpg'} alt={post.title} fill priority sizes="(max-width:900px) 100vw,860px"/></div><div className="prose-card markdown">{blocks.length?blocks.map((block,index)=><p key={index}>{block.replace(/^#+\s*/,'')}</p>):<p>{post.excerpt}</p>}</div></div></article></>}
