'use client';

import { useState } from 'react';
import { ArrowLeft, GripVertical, Plus, Trash2 } from 'lucide-react';
import { ChipListEditor, Field, FormActionBar, FormGrid, ImageListEditor, MultiSelectChips, NumberInput, SectionCard, SelectInput, TextArea, TextInput, ToggleField } from './AdminForm';

type RecordData = Record<string, any>;
const COUNTRIES = ['Kenya', 'Tanzania', 'Zanzibar', 'Kenya + Tanzania', 'Safari + Beach'];
const TRAVEL_STYLES = ['Big 5', 'Great Migration', 'Family', 'Honeymoon', 'Senior Friendly', 'Luxury', 'Budget', 'Midrange', 'Safari & Beach', 'Fly-In', 'Photography', 'Cultural Encounters'];
const COMFORT_LEVELS = ['Budget', 'Midrange', 'Luxury', 'Ultra Luxury'];
const TRAVELER_TYPES = ['Solo', 'Couples', 'Families', 'Seniors', 'Groups', 'Honeymooners', 'Photographers', 'Adventure Seekers'];
const BOOKING_AVAILABILITY = ['Available', 'Limited Seats', 'On Request'];
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const emptyDay = (day: number) => ({ day, title: '', subtitle: '', description: '', accommodation: '', meals: '', transport: '', activities: [] });
const emptySeason = () => ({ id: `season-${Date.now()}`, name: '', startDate: '', endDate: '', soloPrice: 0, sharingPrice: 0, currency: 'USD' });

function draftFromTour(tour?: RecordData | null) {
  if (tour) { const { id, createdAt, updatedAt, viewsCount, ...rest } = tour; return rest; }
  return { title: '', slug: '', shortDescription: '', fullDescription: '', country: 'Kenya', destinations: [], durationDays: 3, durationLabel: '3 Days / 2 Nights', startingLocation: 'Nairobi, Kenya', endingLocation: 'Nairobi, Kenya', categories: [], travelStyles: [], comfortLevel: 'Luxury', travelerTypes: [], featured: false, popular: false, recommended: false, priceFrom: 0, currency: 'USD', soloPrice: 0, sharingPrice: 0, residentPriceKES: undefined, seasonalPricing: [], images: [], itinerary: [emptyDay(1)], accommodationSummary: '', mealsSummary: '', includedActivities: [], includedServices: [], exclusions: [], importantInformation: [], childrenPolicy: '', startingDates: 'Daily Departures (Year-Round)', bookingAvailability: 'Available', seo: { title: '', description: '' }, published: false };
}

export function AdminTourForm({ tour, onSave, onCancel }: { tour?: RecordData | null; onSave: (draft: RecordData) => Promise<void>; onCancel: () => void }) {
  const [draft, setDraft] = useState<RecordData>(() => draftFromTour(tour));
  const [slugTouched, setSlugTouched] = useState(!!tour);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const set = (key: string, value: any) => setDraft(current => ({ ...current, [key]: value }));
  const updateDay = (idx: number, patch: RecordData) => set('itinerary', draft.itinerary.map((item: RecordData, i: number) => i === idx ? { ...item, ...patch } : item));
  const updateSeason = (idx: number, patch: RecordData) => set('seasonalPricing', draft.seasonalPricing.map((item: RecordData, i: number) => i === idx ? { ...item, ...patch } : item));
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError(null);
    if (!draft.title.trim() || !draft.slug.trim()) { setError('Title and slug are required.'); return; }
    setIsSaving(true);
    try { await onSave({ ...draft, durationLabel: draft.durationLabel || `${draft.durationDays} Days / ${Math.max(draft.durationDays - 1, 0)} Nights`, seo: { ...draft.seo, title: draft.seo?.title || draft.title, description: draft.seo?.description || draft.shortDescription } }); }
    catch (err) { setError(err instanceof Error ? err.message : 'Failed to save tour.'); setIsSaving(false); }
  }
  return <form onSubmit={submit} className="space-y-6">
    <div className="flex items-center gap-3"><button type="button" onClick={onCancel} aria-label="Back to tours" className="min-h-9 min-w-9 flex items-center justify-center rounded-lg hover:bg-[#f4f1e8] text-[#161f19]"><ArrowLeft className="w-4 h-4" /></button><h1 className="font-serif-luxury text-2xl font-bold text-[#161f19]">{tour ? 'Edit safari' : 'New safari'}</h1></div>
    <SectionCard title="Basics"><FormGrid>
      <Field label="Tour title" required><TextInput value={draft.title} onChange={value => { set('title', value); if (!slugTouched) set('slug', slugify(value)); }} required /></Field>
      <Field label="URL slug" required hint="Used in the tour's web address"><TextInput value={draft.slug} onChange={value => { setSlugTouched(true); set('slug', slugify(value)); }} required /></Field>
      <Field label="Country / region"><SelectInput value={draft.country} onChange={value => set('country', value)} options={COUNTRIES} /></Field>
      <Field label="Comfort level"><SelectInput value={draft.comfortLevel} onChange={value => set('comfortLevel', value)} options={COMFORT_LEVELS} /></Field>
      <Field label="Duration (days)"><NumberInput value={draft.durationDays} onChange={value => set('durationDays', value)} min={1} /></Field>
      <Field label="Duration label"><TextInput value={draft.durationLabel} onChange={value => set('durationLabel', value)} /></Field>
      <Field label="Starting location"><TextInput value={draft.startingLocation} onChange={value => set('startingLocation', value)} /></Field>
      <Field label="Ending location"><TextInput value={draft.endingLocation} onChange={value => set('endingLocation', value)} /></Field>
    </FormGrid><Field label="Destinations visited"><ChipListEditor items={draft.destinations || []} onChange={value => set('destinations', value)} /></Field><Field label="Categories"><ChipListEditor items={draft.categories || []} onChange={value => set('categories', value)} /></Field><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><ToggleField label="Featured" description="Highlighted across the site" checked={!!draft.featured} onChange={value => set('featured', value)} /><ToggleField label="Popular" description="Shown with a Popular badge" checked={!!draft.popular} onChange={value => set('popular', value)} /><ToggleField label="Published" description="Visible to website visitors" checked={!!draft.published} onChange={value => set('published', value)} /></div></SectionCard>
    <SectionCard title="Descriptions"><Field label="Short description" required><TextArea value={draft.shortDescription || ''} onChange={value => set('shortDescription', value)} rows={2} /></Field><Field label="Full description" required><TextArea value={draft.fullDescription || ''} onChange={value => set('fullDescription', value)} rows={4} /></Field></SectionCard>
    <SectionCard title="Classification"><Field label="Travel styles"><MultiSelectChips options={TRAVEL_STYLES} selected={draft.travelStyles || []} onChange={value => set('travelStyles', value)} /></Field><Field label="Best suited for"><MultiSelectChips options={TRAVELER_TYPES} selected={draft.travelerTypes || []} onChange={value => set('travelerTypes', value)} /></Field><FormGrid><Field label="Booking availability"><SelectInput value={draft.bookingAvailability || 'Available'} onChange={value => set('bookingAvailability', value)} options={BOOKING_AVAILABILITY} /></Field><Field label="Starting dates"><TextInput value={draft.startingDates || ''} onChange={value => set('startingDates', value)} /></Field></FormGrid></SectionCard>
    <SectionCard title="Pricing"><FormGrid cols={3}><Field label="Currency"><SelectInput value={draft.currency || 'USD'} onChange={value => set('currency', value)} options={['USD','KES']} /></Field><Field label="Price from" required><NumberInput value={draft.priceFrom || 0} onChange={value => set('priceFrom', value)} min={0} /></Field><Field label="Solo traveler price"><NumberInput value={draft.soloPrice || 0} onChange={value => set('soloPrice', value)} min={0} /></Field><Field label="Sharing price (per person)"><NumberInput value={draft.sharingPrice || 0} onChange={value => set('sharingPrice', value)} min={0} /></Field><Field label="Kenyan resident price (KES)"><NumberInput value={draft.residentPriceKES || 0} onChange={value => set('residentPriceKES', value || undefined)} min={0} /></Field></FormGrid>
      <div className="pt-2 space-y-3"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-[#76541a]">Seasonal rates</span><button type="button" onClick={() => set('seasonalPricing', [...(draft.seasonalPricing || []), emptySeason()])} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#9e7120]"><Plus className="w-3.5 h-3.5" />Add season</button></div>{(draft.seasonalPricing || []).map((season: RecordData, idx: number) => <div key={season.id || idx} className="p-4 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] space-y-3"><div className="flex gap-2"><input value={season.name || ''} onChange={e => updateSeason(idx,{name:e.target.value})} placeholder="Peak Season" className="flex-1 min-h-9 px-3 rounded-lg bg-white border border-[#ded8cb]" /><button type="button" onClick={() => set('seasonalPricing', draft.seasonalPricing.filter((_: any, i: number) => i !== idx))} className="p-2 text-rose-600"><Trash2 className="w-4 h-4" /></button></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">{[['startDate','Start (MM-DD)'],['endDate','End (MM-DD)']].map(([key,label]) => <label key={key} className="text-xs"><span className="text-[#707f74] block mb-1">{label}</span><input value={season[key] || ''} onChange={e => updateSeason(idx,{[key]:e.target.value})} className="w-full min-h-9 px-2.5 rounded-lg bg-white border border-[#ded8cb]" /></label>)}{[['soloPrice','Solo price'],['sharingPrice','Sharing price']].map(([key,label]) => <label key={key} className="text-xs"><span className="text-[#707f74] block mb-1">{label}</span><input type="number" value={season[key] || 0} onChange={e => updateSeason(idx,{[key]:Number(e.target.value)})} className="w-full min-h-9 px-2.5 rounded-lg bg-white border border-[#ded8cb]" /></label>)}</div></div>)}</div>
    </SectionCard>
    <SectionCard title="Photos"><ImageListEditor images={draft.images || []} onChange={value => set('images', value)} /></SectionCard>
    <SectionCard title="Day-by-day itinerary"><div className="space-y-4">{(draft.itinerary || []).map((day: RecordData, idx: number) => <div key={idx} className="p-4 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] space-y-3"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-sm font-bold text-[#161f19]"><GripVertical className="w-4 h-4 text-[#c7bfb1]" />Day {day.day}</span><button type="button" onClick={() => set('itinerary', draft.itinerary.filter((_: any, i: number) => i !== idx).map((item: RecordData, i: number) => ({...item,day:i+1})))} className="p-2 text-rose-600"><Trash2 className="w-4 h-4" /></button></div><FormGrid><Field label="Day title"><TextInput value={day.title || ''} onChange={value => updateDay(idx,{title:value})} /></Field><Field label="Subtitle"><TextInput value={day.subtitle || ''} onChange={value => updateDay(idx,{subtitle:value})} /></Field></FormGrid><Field label="Description"><TextArea value={day.description || ''} onChange={value => updateDay(idx,{description:value})} rows={2} /></Field><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Field label="Accommodation"><TextInput value={day.accommodation || ''} onChange={value => updateDay(idx,{accommodation:value})} /></Field><Field label="Meals"><TextInput value={day.meals || ''} onChange={value => updateDay(idx,{meals:value})} /></Field><Field label="Transport"><TextInput value={day.transport || ''} onChange={value => updateDay(idx,{transport:value})} /></Field></div><Field label="Key highlights"><ChipListEditor items={day.activities || []} onChange={value => updateDay(idx,{activities:value})} /></Field></div>)}<button type="button" onClick={() => set('itinerary', [...(draft.itinerary || []), emptyDay((draft.itinerary || []).length + 1)])} className="w-full min-h-11 rounded-xl border border-dashed border-[#ded8cb] text-sm font-bold text-[#9e7120] flex items-center justify-center gap-2"><Plus className="w-4 h-4" />Add day {(draft.itinerary || []).length + 1}</button></div></SectionCard>
    <SectionCard title="Inclusions & practical info"><FormGrid><Field label="Accommodation summary"><TextInput value={draft.accommodationSummary || ''} onChange={value => set('accommodationSummary', value)} /></Field><Field label="Meals summary"><TextInput value={draft.mealsSummary || ''} onChange={value => set('mealsSummary', value)} /></Field></FormGrid><Field label="Included services"><ChipListEditor items={draft.includedServices || []} onChange={value => set('includedServices', value)} /></Field><Field label="Included activities"><ChipListEditor items={draft.includedActivities || []} onChange={value => set('includedActivities', value)} /></Field><Field label="What's excluded"><ChipListEditor items={draft.exclusions || []} onChange={value => set('exclusions', value)} /></Field><Field label="Important information"><ChipListEditor items={draft.importantInformation || []} onChange={value => set('importantInformation', value)} /></Field><Field label="Children's policy"><TextInput value={draft.childrenPolicy || ''} onChange={value => set('childrenPolicy', value)} /></Field></SectionCard>
    <SectionCard title="Search engine details"><Field label="SEO title"><TextInput value={draft.seo?.title || ''} onChange={value => set('seo',{...draft.seo,title:value})} /></Field><Field label="SEO description"><TextArea value={draft.seo?.description || ''} onChange={value => set('seo',{...draft.seo,description:value})} rows={2} /></Field></SectionCard>
    <FormActionBar onCancel={onCancel} isSaving={isSaving} error={error} saveLabel={tour ? 'Save changes' : 'Create safari'} />
  </form>;
}
