'use client';

import { useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import { ChipListEditor, Field, FormActionBar, FormGrid, ImageListEditor, SectionCard, TextArea, TextInput, ToggleField } from './AdminForm';

type RecordData=Record<string,any>;
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function draftFromPost(post?:RecordData|null){if(post){const{id,...rest}=post;return rest;}return{title:'',slug:'',excerpt:'',content:'',featuredImage:'',author:{name:'',role:'Travel Specialist',avatar:''},publishedDate:new Date().toISOString().slice(0,10),category:'Safari Travel',readingTime:'5 min read',relatedDestinations:[],relatedTours:[],tags:[],published:false};}
export function AdminBlogForm({post,defaultAuthorName,onSave,onCancel}:{post?:RecordData|null;defaultAuthorName?:string;onSave:(draft:RecordData)=>Promise<void>;onCancel:()=>void}){
 const[draft,setDraft]=useState<RecordData>(()=>{const base=draftFromPost(post);if(!post&&defaultAuthorName)base.author.name=defaultAuthorName;return base;});const[slugTouched,setSlugTouched]=useState(!!post);const[isSaving,setIsSaving]=useState(false);const[error,setError]=useState<string|null>(null);const set=(key:string,value:any)=>setDraft(current=>({...current,[key]:value}));
 async function submit(event:React.FormEvent){event.preventDefault();setError(null);if(!draft.title.trim()||!draft.slug.trim()){setError('Title and slug are required.');return;}setIsSaving(true);try{await onSave(draft)}catch(err){setError(err instanceof Error?err.message:'Failed to save article.');setIsSaving(false)}}
 return <form onSubmit={submit} className="space-y-6"><div className="flex items-center gap-3"><button type="button" onClick={onCancel} aria-label="Back to blog" className="min-h-9 min-w-9 flex items-center justify-center rounded-lg hover:bg-[#f4f1e8] text-[#161f19]"><ArrowLeft className="w-4 h-4"/></button><h1 className="font-serif-luxury text-2xl font-bold text-[#161f19]">{post?'Edit article':'New article'}</h1></div><SectionCard title="Article"><FormGrid><Field label="Title" required><TextInput value={draft.title} onChange={value=>{set('title',value);if(!slugTouched)set('slug',slugify(value));}} required/></Field><Field label="URL slug" required><TextInput value={draft.slug} onChange={value=>{setSlugTouched(true);set('slug',slugify(value));}} required/></Field><Field label="Category"><TextInput value={draft.category||''} onChange={value=>set('category',value)}/></Field><Field label="Reading time"><TextInput value={draft.readingTime||''} onChange={value=>set('readingTime',value)}/></Field><Field label="Published date"><TextInput value={(draft.publishedDate||'').slice(0,10)} onChange={value=>set('publishedDate',value)} type="date"/></Field></FormGrid><Field label="Featured image"><ImageListEditor images={draft.featuredImage?[draft.featuredImage]:[]} maxImages={1} onChange={images=>set('featuredImage',images[0]||'')}/></Field><Field label="Excerpt"><TextArea value={draft.excerpt||''} onChange={value=>set('excerpt',value)} rows={2}/></Field><Field label="Full article content"><TextArea value={draft.content||''} onChange={value=>set('content',value)} rows={10}/></Field><ToggleField label="Published" description="Visible to website visitors" checked={!!draft.published} onChange={value=>set('published',value)}/></SectionCard><SectionCard title="Author"><FormGrid cols={3}><Field label="Name"><TextInput value={draft.author?.name||''} onChange={value=>set('author',{...draft.author,name:value})}/></Field><Field label="Role"><TextInput value={draft.author?.role||''} onChange={value=>set('author',{...draft.author,role:value})}/></Field><Field label="Avatar image URL"><TextInput value={draft.author?.avatar||''} onChange={value=>set('author',{...draft.author,avatar:value})} type="url"/></Field></FormGrid></SectionCard><SectionCard title="Related content & tags"><Field label="Tags"><ChipListEditor items={draft.tags||[]} onChange={value=>set('tags',value)}/></Field><Field label="Related destination names"><ChipListEditor items={draft.relatedDestinations||[]} onChange={value=>set('relatedDestinations',value)}/></Field><Field label="Related tour titles"><ChipListEditor items={draft.relatedTours||[]} onChange={value=>set('relatedTours',value)}/></Field></SectionCard><FormActionBar onCancel={onCancel} isSaving={isSaving} error={error} saveLabel={post?'Save changes':'Publish draft'}/></form>;
}
