'use client';

import { useState } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { ChipListEditor, Field, FormActionBar, FormGrid, ImageListEditor, SectionCard, SelectInput, TextArea, TextInput, ToggleField } from './AdminForm';

type RecordData=Record<string,any>;
const COUNTRIES=['Kenya','Tanzania','Zanzibar'];
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function draftFromDestination(destination?:RecordData|null){if(destination){const{id,...rest}=destination;return rest;}return{name:'',slug:'',country:'Kenya',subtitle:'',description:'',heroImage:'',gallery:[],bestTimeToVisit:'Year-round',wildlife:[],activities:[],recommendedDuration:'2-3 days',thingsToDo:[],whereToStay:'',featured:false,faqs:[],seo:{title:'',description:''},published:false};}
export function AdminDestinationForm({destination,onSave,onCancel}:{destination?:RecordData|null;onSave:(draft:RecordData)=>Promise<void>;onCancel:()=>void}){
 const[draft,setDraft]=useState<RecordData>(()=>draftFromDestination(destination));const[slugTouched,setSlugTouched]=useState(!!destination);const[isSaving,setIsSaving]=useState(false);const[error,setError]=useState<string|null>(null);const set=(key:string,value:any)=>setDraft(current=>({...current,[key]:value}));const updateFaq=(idx:number,patch:RecordData)=>set('faqs',(draft.faqs||[]).map((item:RecordData,i:number)=>i===idx?{...item,...patch}:item));
 async function submit(event:React.FormEvent){event.preventDefault();setError(null);if(!draft.name.trim()||!draft.slug.trim()){setError('Name and slug are required.');return;}setIsSaving(true);try{await onSave({...draft,seo:{title:draft.seo?.title||draft.name,description:draft.seo?.description||draft.description}})}catch(err){setError(err instanceof Error?err.message:'Failed to save destination.');setIsSaving(false)}}
 return <form onSubmit={submit} className="space-y-6"><div className="flex items-center gap-3"><button type="button" onClick={onCancel} aria-label="Back to destinations" className="min-h-9 min-w-9 flex items-center justify-center rounded-lg hover:bg-[#f4f1e8] text-[#161f19]"><ArrowLeft className="w-4 h-4"/></button><h1 className="font-serif-luxury text-2xl font-bold text-[#161f19]">{destination?'Edit destination':'New destination'}</h1></div>
 <SectionCard title="Basics"><FormGrid><Field label="Name" required><TextInput value={draft.name} onChange={value=>{set('name',value);if(!slugTouched)set('slug',slugify(value));}} required/></Field><Field label="URL slug" required><TextInput value={draft.slug} onChange={value=>{setSlugTouched(true);set('slug',slugify(value));}} required/></Field><Field label="Country"><SelectInput value={draft.country} onChange={value=>set('country',value)} options={COUNTRIES}/></Field><Field label="Recommended duration"><TextInput value={draft.recommendedDuration||''} onChange={value=>set('recommendedDuration',value)}/></Field><Field label="Best time to visit"><TextInput value={draft.bestTimeToVisit||''} onChange={value=>set('bestTimeToVisit',value)}/></Field></FormGrid><Field label="Subtitle"><TextInput value={draft.subtitle||''} onChange={value=>set('subtitle',value)}/></Field><Field label="Description"><TextArea value={draft.description||''} onChange={value=>set('description',value)} rows={3}/></Field><Field label="Where to stay"><TextArea value={draft.whereToStay||''} onChange={value=>set('whereToStay',value)} rows={2}/></Field><ToggleField label="Featured" description="Highlighted on the homepage" checked={!!draft.featured} onChange={value=>set('featured',value)}/><ToggleField label="Published" description="Visible to website visitors" checked={!!draft.published} onChange={value=>set('published',value)}/></SectionCard>
 <SectionCard title="Photos" description="The first image is the cover. Upload new files or promote any gallery image."><ImageListEditor images={[draft.heroImage,...(draft.gallery||[])].filter(Boolean)} onChange={images=>setDraft(current=>({...current,heroImage:images[0]||'',gallery:images.slice(1)}))}/></SectionCard>
 <SectionCard title="Wildlife & activities"><Field label="Iconic wildlife"><ChipListEditor items={draft.wildlife||[]} onChange={value=>set('wildlife',value)}/></Field><Field label="Activities"><ChipListEditor items={draft.activities||[]} onChange={value=>set('activities',value)}/></Field><Field label="Things to do"><ChipListEditor items={draft.thingsToDo||[]} onChange={value=>set('thingsToDo',value)}/></Field></SectionCard>
 <SectionCard title="Frequently asked questions"><div className="space-y-3">{(draft.faqs||[]).map((faq:RecordData,idx:number)=><div key={idx} className="p-4 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] space-y-2"><div className="flex gap-2"><input value={faq.question||''} onChange={e=>updateFaq(idx,{question:e.target.value})} placeholder="Question" className="flex-1 min-h-9 px-3 rounded-lg bg-white border border-[#ded8cb] text-sm font-semibold"/><button type="button" onClick={()=>set('faqs',draft.faqs.filter((_:any,i:number)=>i!==idx))} className="p-2 text-rose-600"><Trash2 className="w-4 h-4"/></button></div><textarea value={faq.answer||''} onChange={e=>updateFaq(idx,{answer:e.target.value})} placeholder="Answer" rows={2} className="w-full px-3 py-2 rounded-lg bg-white border border-[#ded8cb] text-sm resize-y"/></div>)}<button type="button" onClick={()=>set('faqs',[...(draft.faqs||[]),{question:'',answer:''}])} className="w-full min-h-11 rounded-xl border border-dashed border-[#ded8cb] text-sm font-bold text-[#9e7120] flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>Add question</button></div></SectionCard>
 <SectionCard title="Search engine details"><Field label="SEO title"><TextInput value={draft.seo?.title||''} onChange={value=>set('seo',{...draft.seo,title:value})}/></Field><Field label="SEO description"><TextArea value={draft.seo?.description||''} onChange={value=>set('seo',{...draft.seo,description:value})} rows={2}/></Field></SectionCard><FormActionBar onCancel={onCancel} isSaving={isSaving} error={error} saveLabel={destination?'Save changes':'Create destination'}/></form>;
}
