'use client';

import { useState } from 'react';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { ChipListEditor, Field, FormActionBar, FormGrid, ImageListEditor, NumberInput, SectionCard, SelectInput, TextArea, TextInput, ToggleField } from './AdminForm';
import { createStandardHotelSeasons } from '../../lib/seasonalPricing';

type RecordData = Record<string, any>;
const COUNTRIES = ['Kenya', 'Tanzania', 'Zanzibar'];
const CATEGORIES = ['Luxury Safari Lodge', 'Tented Camp', 'Beach Resort & Spa', 'Boutique Hotel', 'Eco Lodge'];
const slugify = (value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const emptySeason = () => ({ seasonName:'', dates:'', priceKES:0, priceUSD:0 });
function draftFromHotel(hotel?:RecordData|null){ if(hotel){const{id,...rest}=hotel;return rest;} return {name:'',slug:'',location:'',country:'Kenya',description:'',category:'Beach Resort & Spa',images:[],priceFromUSD:0,priceFromKES:0,soloPriceUSD:0,sharingPriceUSD:0,seasonalPricing:createStandardHotelSeasons(),facilities:[],roomTypes:[],inclusions:[],exclusions:[],isFamilyFriendly:false,isHoneymoonFriendly:false,isSeniorFriendly:false,isKenyanResidentOffer:false,bookingLink:'',rating:undefined,seo:{title:'',description:''},published:false}; }
export function AdminHotelForm({hotel,onSave,onCancel}:{hotel?:RecordData|null;onSave:(draft:RecordData)=>Promise<void>;onCancel:()=>void}){
 const[draft,setDraft]=useState<RecordData>(()=>draftFromHotel(hotel));const[slugTouched,setSlugTouched]=useState(!!hotel);const[isSaving,setIsSaving]=useState(false);const[error,setError]=useState<string|null>(null);const set=(key:string,value:any)=>setDraft(current=>({...current,[key]:value}));const updateSeason=(idx:number,patch:RecordData)=>set('seasonalPricing',(draft.seasonalPricing||[]).map((item:RecordData,i:number)=>i===idx?{...item,...patch}:item));
 async function submit(event:React.FormEvent){event.preventDefault();setError(null);if(!draft.name.trim()||!draft.slug.trim()){setError('Name and slug are required.');return;}setIsSaving(true);try{await onSave({...draft,seo:{...draft.seo,title:draft.seo?.title||draft.name,description:draft.seo?.description||draft.description}})}catch(err){setError(err instanceof Error?err.message:'Failed to save hotel.');setIsSaving(false)}}
 return <form onSubmit={submit} className="space-y-6"><div className="flex items-center gap-3"><button type="button" onClick={onCancel} aria-label="Back to hotels" className="min-h-9 min-w-9 flex items-center justify-center rounded-lg hover:bg-[#f4f1e8] text-[#161f19]"><ArrowLeft className="w-4 h-4"/></button><h1 className="font-serif-luxury text-2xl font-bold text-[#161f19]">{hotel?'Edit hotel':'New hotel'}</h1></div>
 <SectionCard title="Basics"><FormGrid><Field label="Hotel name" required><TextInput value={draft.name} onChange={value=>{set('name',value);if(!slugTouched)set('slug',slugify(value));}} required/></Field><Field label="URL slug" required><TextInput value={draft.slug} onChange={value=>{setSlugTouched(true);set('slug',slugify(value));}} required/></Field><Field label="Location"><TextInput value={draft.location||''} onChange={value=>set('location',value)}/></Field><Field label="Country"><SelectInput value={draft.country} onChange={value=>set('country',value)} options={COUNTRIES}/></Field><Field label="Category"><SelectInput value={draft.category} onChange={value=>set('category',value)} options={CATEGORIES}/></Field><Field label="Rating (out of 5)"><NumberInput value={draft.rating||0} onChange={value=>set('rating',value||undefined)} min={0} max={5} step={0.1}/></Field></FormGrid><Field label="Description"><TextArea value={draft.description||''} onChange={value=>set('description',value)} rows={3}/></Field><div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><ToggleField label="Family friendly" checked={!!draft.isFamilyFriendly} onChange={value=>set('isFamilyFriendly',value)}/><ToggleField label="Honeymoon friendly" checked={!!draft.isHoneymoonFriendly} onChange={value=>set('isHoneymoonFriendly',value)}/><ToggleField label="Senior friendly" checked={!!draft.isSeniorFriendly} onChange={value=>set('isSeniorFriendly',value)}/><ToggleField label="Kenyan resident offer" checked={!!draft.isKenyanResidentOffer} onChange={value=>set('isKenyanResidentOffer',value)}/></div><ToggleField label="Published" description="Visible to website visitors" checked={!!draft.published} onChange={value=>set('published',value)}/></SectionCard>
 <SectionCard title="Pricing"><FormGrid cols={3}><Field label="Price from (USD / night)"><NumberInput value={draft.priceFromUSD||0} onChange={value=>set('priceFromUSD',value)} min={0}/></Field><Field label="Price from (KES / night)"><NumberInput value={draft.priceFromKES||0} onChange={value=>set('priceFromKES',value)} min={0}/></Field><Field label="Booking link"><TextInput value={draft.bookingLink||''} onChange={value=>set('bookingLink',value)} type="url"/></Field><Field label="Solo price (USD)"><NumberInput value={draft.soloPriceUSD||0} onChange={value=>set('soloPriceUSD',value)} min={0}/></Field><Field label="Sharing price (USD)"><NumberInput value={draft.sharingPriceUSD||0} onChange={value=>set('sharingPriceUSD',value)} min={0}/></Field></FormGrid><div className="pt-2 space-y-3"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-[#76541a]">Seasonal rates</span><button type="button" onClick={()=>set('seasonalPricing',[...(draft.seasonalPricing||[]),emptySeason()])} className="inline-flex items-center gap-1.5 text-xs font-bold text-[#9e7120]"><Plus className="w-3.5 h-3.5"/>Add season</button></div>{(draft.seasonalPricing||[]).map((season:RecordData,idx:number)=><div key={idx} className="p-4 rounded-xl bg-[#faf8f2] border border-[#e3ddcf] space-y-3"><div className="flex gap-2"><input value={season.seasonName||''} onChange={e=>updateSeason(idx,{seasonName:e.target.value})} className="flex-1 min-h-9 px-3 rounded-lg bg-white border border-[#ded8cb]" placeholder="Peak Season"/><button type="button" onClick={()=>set('seasonalPricing',draft.seasonalPricing.filter((_:any,i:number)=>i!==idx))} className="p-2 text-rose-600"><Trash2 className="w-4 h-4"/></button></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">{[['dates','Dates']].map(([key,label])=><label key={key} className="text-xs"><span className="text-[#707f74] block mb-1">{label}</span><input value={season[key]||''} onChange={e=>updateSeason(idx,{[key]:e.target.value})} className="w-full min-h-9 px-2.5 rounded-lg bg-white border border-[#ded8cb]"/></label>)}{[['priceKES','Price (KES)'],['priceUSD','Price (USD)']].map(([key,label])=><label key={key} className="text-xs"><span className="text-[#707f74] block mb-1">{label}</span><input type="number" value={season[key]||0} onChange={e=>updateSeason(idx,{[key]:Number(e.target.value)})} className="w-full min-h-9 px-2.5 rounded-lg bg-white border border-[#ded8cb]"/></label>)}</div></div>)}</div></SectionCard>
 <SectionCard title="Photos"><ImageListEditor images={draft.images||[]} onChange={value=>set('images',value)}/></SectionCard><SectionCard title="Amenities & policies"><Field label="Facilities"><ChipListEditor items={draft.facilities||[]} onChange={value=>set('facilities',value)}/></Field><Field label="Room types"><ChipListEditor items={draft.roomTypes||[]} onChange={value=>set('roomTypes',value)}/></Field><Field label="Inclusions"><ChipListEditor items={draft.inclusions||[]} onChange={value=>set('inclusions',value)}/></Field><Field label="Exclusions"><ChipListEditor items={draft.exclusions||[]} onChange={value=>set('exclusions',value)}/></Field></SectionCard><SectionCard title="Search engine details"><Field label="SEO title"><TextInput value={draft.seo?.title||''} onChange={value=>set('seo',{...draft.seo,title:value})}/></Field><Field label="SEO description"><TextArea value={draft.seo?.description||''} onChange={value=>set('seo',{...draft.seo,description:value})} rows={2}/></Field></SectionCard><FormActionBar onCancel={onCancel} isSaving={isSaving} error={error} saveLabel={hotel?'Save changes':'Create hotel'}/></form>;
}
