'use client';

import { useState } from 'react';
import { ImageOff, Loader2, Plus, Save, X } from 'lucide-react';

export const fieldBaseClass = 'w-full min-h-11 px-3.5 py-2.5 rounded-xl bg-[#faf8f2] border border-[#ded8cb] text-sm text-[#161f19] focus:border-[#b3822a] focus:outline-none focus:ring-2 focus:ring-[#b3822a]/15 transition-colors';
export function Field({ label, hint, required, children, className }: { label: string; hint?: string; required?: boolean; children: React.ReactNode; className?: string }) { return <label className={`block ${className || ''}`}><span className="text-xs font-bold uppercase tracking-wider text-[#76541a] mb-1.5 block">{label}{required ? <span className="text-rose-600 ml-0.5">*</span> : null}</span>{children}{hint ? <span className="text-xs text-[#707f74] mt-1 block">{hint}</span> : null}</label>; }
export function TextInput({ value, onChange, placeholder, type = 'text', required }: { value: string; onChange: (v: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} required={required} className={fieldBaseClass} />; }
export function NumberInput({ value, onChange, min, max, step }: { value: number; onChange: (v: number) => void; min?: number; max?: number; step?: number }) { return <input type="number" value={Number.isFinite(value) ? value : 0} onChange={event => onChange(event.target.value === '' ? 0 : Number(event.target.value))} min={min} max={max} step={step} className={fieldBaseClass} />; }
export function TextArea({ value, onChange, rows = 3, placeholder }: { value: string; onChange: (v: string) => void; rows?: number; placeholder?: string }) { return <textarea value={value} onChange={event => onChange(event.target.value)} rows={rows} placeholder={placeholder} className={`${fieldBaseClass} resize-y leading-relaxed`} />; }
export function SelectInput({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: readonly string[] | { value: string; label: string }[] }) { return <select value={value} onChange={event => onChange(event.target.value)} className={`${fieldBaseClass} cursor-pointer`}>{options.map(option => { const item = typeof option === 'string' ? { value: option, label: option } : option; return <option key={item.value} value={item.value}>{item.label}</option>; })}</select>; }
export function ToggleField({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (v: boolean) => void }) { return <button type="button" onClick={() => onChange(!checked)} aria-pressed={checked} className={`w-full flex items-center justify-between gap-3 p-3.5 rounded-xl border text-left transition-colors ${checked ? 'bg-[#eef7f2] border-[#b6d8c3]' : 'bg-[#faf8f2] border-[#ded8cb]'}`}><span><span className="text-sm font-semibold text-[#161f19] block">{label}</span>{description ? <span className="text-xs text-[#707f74] block mt-0.5">{description}</span> : null}</span><span className={`shrink-0 w-10 h-6 rounded-full relative transition-colors ${checked ? 'bg-[#1b4332]' : 'bg-[#d7d1c4]'}`}><span className={`absolute top-0.5 w-5 h-5 rounded-full bg-white shadow-sm transition-transform ${checked ? 'translate-x-[18px]' : 'translate-x-0.5'}`} /></span></button>; }
export function ChipListEditor({ items, onChange, placeholder = 'Add an item and press Enter' }: { items: string[]; onChange: (items: string[]) => void; placeholder?: string }) { const [draft, setDraft] = useState(''); const commit = () => { const trimmed = draft.trim(); if (!trimmed) return; onChange([...items, trimmed]); setDraft(''); }; return <div className="space-y-2.5">{items.length ? <div className="flex flex-wrap gap-2">{items.map((item, index) => <span key={`${item}-${index}`} className="inline-flex items-center gap-1.5 pl-3 pr-2 py-1.5 rounded-lg bg-[#f4f1e8] border border-[#e2ddd0] text-xs font-medium text-[#303e35]">{item}<button type="button" onClick={() => onChange(items.filter((_, i) => i !== index))} aria-label={`Remove ${item}`} className="text-[#9a917f] hover:text-rose-600"><X className="w-3.5 h-3.5" /></button></span>)}</div> : null}<div className="flex gap-2"><input type="text" value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); commit(); } }} placeholder={placeholder} className={fieldBaseClass} /><button type="button" onClick={commit} className="shrink-0 min-h-11 px-3.5 rounded-xl bg-[#f4f1e8] hover:bg-[#eae5d8] border border-[#ded8cb] text-[#161f19]" aria-label="Add item"><Plus className="w-4 h-4" /></button></div></div>; }
export function ImageListEditor({ images, onChange }: { images: string[]; onChange: (images: string[]) => void }) { const [draft, setDraft] = useState(''); const commit = () => { const trimmed = draft.trim(); if (!trimmed) return; onChange([...images, trimmed]); setDraft(''); }; return <div className="space-y-3">{images.length ? <div className="grid grid-cols-3 sm:grid-cols-4 gap-2.5">{images.map((src, index) => <div key={`${src}-${index}`} className="relative group aspect-square rounded-xl overflow-hidden border border-[#ded8cb] bg-[#f4f1e8]"><img src={src} alt={`Image ${index + 1}`} className="w-full h-full object-cover" onError={event => { (event.target as HTMLImageElement).style.display = 'none'; }} /><button type="button" onClick={() => onChange(images.filter((_, i) => i !== index))} aria-label={`Remove image ${index + 1}`} className="absolute top-1 right-1 p-1 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 focus:opacity-100 transition-opacity"><X className="w-3.5 h-3.5" /></button>{index === 0 ? <span className="absolute bottom-1 left-1 px-1.5 py-0.5 rounded bg-black/60 text-white text-[10px] font-bold uppercase">Cover</span> : null}</div>)}</div> : <div className="flex items-center gap-2 p-3 rounded-xl border border-dashed border-[#d7d1c4] text-xs text-[#707f74]"><ImageOff className="w-4 h-4 shrink-0" />No images yet. The first image added becomes the cover photo.</div>}<div className="flex gap-2"><input type="url" value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); commit(); } }} placeholder="Paste an image URL" className={fieldBaseClass} /><button type="button" onClick={commit} className="shrink-0 min-h-11 px-3.5 rounded-xl bg-[#f4f1e8] hover:bg-[#eae5d8] border border-[#ded8cb] text-[#161f19]" aria-label="Add image"><Plus className="w-4 h-4" /></button></div></div>; }
export function MultiSelectChips({ options, selected, onChange }: { options: readonly string[]; selected: string[]; onChange: (selected: string[]) => void }) { return <div className="flex flex-wrap gap-2">{options.map(option => { const isSelected = selected.includes(option); return <button key={option} type="button" aria-pressed={isSelected} onClick={() => onChange(isSelected ? selected.filter(item => item !== option) : [...selected, option])} className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-colors ${isSelected ? 'bg-[#1b4332] text-white border-[#1b4332]' : 'bg-[#faf8f2] text-[#405046] border-[#ded8cb] hover:border-[#b3822a]'}`}>{option}</button>; })}</div>; }
export function SectionCard({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <div className="p-5 sm:p-6 rounded-2xl bg-white border border-[#e8e4da] space-y-4 shadow-xs"><div><h3 className="font-serif-luxury text-lg font-bold text-[#161f19]">{title}</h3>{description ? <p className="text-xs text-[#707f74] mt-0.5">{description}</p> : null}</div>{children}</div>; }
export function FormActionBar({ onCancel, isSaving, saveLabel = 'Save changes', error }: { onCancel: () => void; isSaving: boolean; saveLabel?: string; error?: string | null }) { return <div className="sticky bottom-0 -mx-4 sm:-mx-8 px-4 sm:px-8 py-4 bg-[#faf8f2]/95 backdrop-blur-xl border-t border-[#e8e4da] flex items-center justify-between gap-4"><span className="text-xs text-rose-700 font-medium">{error}</span><div className="flex items-center gap-3 ml-auto"><button type="button" onClick={onCancel} className="min-h-11 px-5 rounded-xl bg-white border border-[#ded8cb] text-[#161f19] text-sm font-semibold hover:bg-[#f4f1e8]">Cancel</button><button type="submit" disabled={isSaving} className="min-h-11 px-6 rounded-xl bg-[#b3822a] hover:bg-[#9e7120] disabled:opacity-60 text-white text-sm font-bold flex items-center gap-2 shadow-sm">{isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}<span>{isSaving ? 'Saving…' : saveLabel}</span></button></div></div>; }
export function FormGrid({ children, cols = 2 }: { children: React.ReactNode; cols?: 2 | 3 }) { return <div className={`grid grid-cols-1 ${cols === 3 ? 'sm:grid-cols-3' : 'sm:grid-cols-2'} gap-4`}>{children}</div>; }
