import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Binoculars, CheckCircle2, Compass, Heart, Palmtree, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { DestinationCard, HotelCard, ReviewCard, TourCard } from '../components/CatalogCards';
import { EnquiryButton } from '../components/EnquiryButton';
import { SafariFinderBar } from '../components/SafariFinderBar';
import { getBlogPosts, getDestinations, getHotels, getTestimonials, getTours } from '../lib/api';

export const revalidate=900;
export const metadata:Metadata={title:'Good Secrets Safaris',description:'Private Kenya, Tanzania and Zanzibar safaris planned with an East Africa-based team. Explore itinerary ideas, independent reviews and tailor-made safari planning.',alternates:{canonical:'/'},openGraph:{title:'Good Secrets Safaris | Your safari. Our home.',description:'Private Kenya, Tanzania and Zanzibar safaris planned around your dates, interests and travel style.',url:'/',images:['/images/catalog/vehicle-next-to-the-great-migration.jpg']}};

const styles=[['Big 5',Binoculars,'Classic private game drives built around East Africa’s iconic wildlife.'],['Great Migration',Compass,'Mara and Serengeti timing for one of Africa’s great wildlife movements.'],['Family',Users,'Flexible pacing, practical logistics and family-friendly stays.'],['Honeymoon',Heart,'Private wildlife time, intimate camps and beach combinations.'],['Luxury',Sparkles,'Exceptional lodges, private conservancies and fly-in possibilities.'],['Safari & Beach',Palmtree,'Combine the bush with Diani, Watamu or Zanzibar.']] as const;

export default async function HomePage(){const[tours,destinations,hotels,reviews,blogPosts]=await Promise.all([getTours(),getDestinations(),getHotels(),getTestimonials(),getBlogPosts()]);const featured=tours.filter(t=>t.featured||t.popular);const featuredTours=(featured.length?featured:tours).slice(0,6);return <div className="pb-20 space-y-20 sm:space-y-28 bg-shell">
  <section className="hero"><div className="hero-media"><Image src="/images/catalog/vehicle-next-to-the-great-migration.jpg" alt="Safari vehicle watching the Great Migration in East Africa" fill priority sizes="100vw"/></div><div className="hero-overlay"/><div className="hero-content"><div className="max-w-4xl space-y-6"><span className="inline-flex items-center gap-2 rounded-full bg-black/45 backdrop-blur-md px-4 py-2 border border-white/25 text-brand-soft text-xs font-bold uppercase tracking-widest"><Compass className="w-4 h-4"/>Private safaris · Kenya · Tanzania · Zanzibar</span><h1>Your safari. Our home.</h1><p>Private 4x4 journeys, experienced local guides and carefully chosen stays — shaped around your dates, pace and priorities.</p><div className="flex flex-col sm:flex-row gap-3 max-w-3xl"><Link href="/safari-builder" className="min-h-12 px-7 rounded-xl bg-brand-soft hover:bg-brand text-ink-strong font-extrabold text-sm shadow-xl inline-flex items-center justify-center">Build My Safari</Link><Link href="/safaris" className="min-h-12 px-7 rounded-xl border border-white/30 bg-black/25 hover:bg-black/40 text-white font-bold text-sm backdrop-blur-sm inline-flex items-center justify-center">Explore Safari Ideas</Link><Link href="/plan-with-us" className="min-h-12 px-5 text-white/95 hover:text-brand-soft font-bold text-sm inline-flex items-center">How we plan your safari →</Link></div><div className="hero-proof"><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-brand-soft"/>No payment to enquire</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-brand-soft"/>Private 4x4</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="w-4 h-4 text-brand-soft"/>Flexible dates & pacing</span></div><div className="pt-4"><SafariFinderBar/></div></div></div></section>

  {reviews.length>0&&<section className="max-w-7xl mx-auto px-4 sm:px-8"><div className="rounded-[2rem] bg-page border border-border-strong p-6 sm:p-8 text-ink"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-deep">Independent traveler feedback</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-ink-strong mt-1">What travelers say after the safari.</h2><p className="text-sm text-ink-muted mt-2">Use the original Tripadvisor and SafariBookings profiles as the current source of truth.</p></div><Link href="/reviews" className="font-bold text-brand-deep">See all reviews →</Link></div><div className="grid-3">{reviews.slice(0,3).map(r=><ReviewCard key={r.id} review={r}/>)}</div></div></section>}

  <section className="max-w-7xl mx-auto px-4 sm:px-8 grid lg:grid-cols-12 gap-8 lg:gap-14 items-center"><div className="lg:col-span-5 space-y-5"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Personal planning, on the ground</span><h2 className="font-serif-luxury text-3xl sm:text-5xl font-bold text-white leading-tight">A safari is too important to feel anonymous.</h2><p className="text-base text-on-shell-muted leading-relaxed">You should understand who is shaping your route, what is included and how to get help while you travel. We plan private East Africa journeys around real people rather than treating an itinerary as a checkout product.</p><div className="grid sm:grid-cols-2 gap-3">{[['1','Tell us your priorities'],['2','Refine route & stays'],['3','Review before committing'],['4','Travel with local support']].map(([n,label])=><div key={n} className="border-t border-white/15 pt-3"><span className="font-serif-luxury text-xl text-brand-soft">{n}</span><strong className="text-sm text-white ml-3">{label}</strong></div>)}</div><Link href="/plan-with-us" className="min-h-11 inline-flex items-center gap-2 text-brand-soft hover:text-white font-bold text-sm">See how we plan your safari <ArrowRight className="w-4 h-4"/></Link></div><div className="lg:col-span-7 grid grid-cols-5 gap-3 sm:gap-4"><div className="col-span-3 row-span-2 rounded-[2rem] overflow-hidden min-h-80 border border-white/10 relative"><Image src="/images/catalog/family-safari-game-drive.jpg" alt="Travelers enjoying a private safari game drive" fill className="object-cover"/></div><div className="col-span-2 rounded-[2rem] overflow-hidden min-h-40 border border-white/10 relative"><Image src="/images/catalog/picnic-lunch-in-the-wild.jpg" alt="Safari picnic lunch in the wild" fill className="object-cover"/></div><div className="col-span-2 rounded-[2rem] overflow-hidden min-h-40 border border-white/10 relative"><Image src="/images/catalog/honey-moon-in-samburu.jpg" alt="Couple enjoying a Samburu safari" fill className="object-cover"/></div></div></section>

  <section className="max-w-7xl mx-auto px-4 sm:px-8 space-y-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Safari ideas</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white mt-1">Start with a proven route. Make it yours.</h2><p className="text-base text-on-shell-muted mt-2 max-w-2xl">Compare duration, country and guide price, then adjust dates, accommodation and pacing with the safari team.</p></div><Link href="/safaris" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-brand-soft">View all {tours.length} safari ideas <ArrowRight className="w-4 h-4"/></Link></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{featuredTours.map(t=><TourCard key={t.id} tour={t}/>)}</div></section>

  <section className="max-w-7xl mx-auto px-4 sm:px-8"><div className="rounded-[2rem] bg-page border border-border-strong p-7 sm:p-10 lg:p-12 text-ink-strong"><div className="grid lg:grid-cols-12 gap-10"><div className="lg:col-span-4"><span className="text-xs font-extrabold uppercase tracking-widest text-brand-deep">Choose the feeling first</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold mt-2">What kind of safari are you imagining?</h2><p className="text-sm text-ink-muted mt-3 leading-relaxed">Use these as starting points rather than boxes you have to fit into.</p></div><div className="lg:col-span-8 grid sm:grid-cols-2 gap-x-8">{styles.map(([title,Icon,desc])=><Link key={title} href={`/safaris?travelStyle=${encodeURIComponent(title)}`} className="group text-left py-5 border-b border-border-strong flex gap-4"><span className="w-11 h-11 shrink-0 rounded-full border border-border-strong flex items-center justify-center text-brand-deep group-hover:bg-action group-hover:text-white transition-colors"><Icon className="w-5 h-5"/></span><span><strong className="font-serif-luxury text-xl block group-hover:text-brand-deep">{title}</strong><span className="text-sm text-ink-muted mt-1 block leading-relaxed">{desc}</span></span></Link>)}</div></div></div></section>

  <section className="max-w-7xl mx-auto px-4 sm:px-8 space-y-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Destination guides</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white mt-1">Learn the parks before choosing the route.</h2><p className="text-base text-on-shell-muted mt-2">Wildlife, seasons and route ideas across East Africa.</p></div><Link href="/destinations" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-brand-soft">All destinations <ArrowRight className="w-4 h-4"/></Link></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{destinations.slice(0,6).map(d=><DestinationCard key={d.id} destination={d}/>)}</div></section>

  <section className="max-w-7xl mx-auto px-4 sm:px-8 grid lg:grid-cols-12 gap-8 items-center"><div className="lg:col-span-6 rounded-[2rem] overflow-hidden aspect-[4/3] border border-white/10 relative"><Image src="/images/catalog/sundowner-at-amboseli.jpg" alt="Sundowner experience in Amboseli" fill className="object-cover"/></div><div className="lg:col-span-6 space-y-5"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Why Good Secrets</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white">Local expertise is most useful when it changes the trip.</h2><div className="space-y-4">{[['Personal planning','Change the route, pace and accommodation around the people actually traveling.'],['Independent proof','Use independent traveler reviews to verify what past guests say.'],['Local communication','Email, phone and WhatsApp keep the East Africa team within reach.'],['Clarity before commitment','Review itinerary, inclusions and trip terms before deciding to proceed.']].map(([title,desc])=><div key={title} className="flex gap-3"><ShieldCheck className="w-5 h-5 text-brand-soft shrink-0 mt-0.5"/><div><strong className="text-white">{title}</strong><p className="text-sm text-on-shell-muted mt-1">{desc}</p></div></div>)}</div><div className="flex flex-wrap gap-4"><Link href="/about" className="min-h-11 inline-flex items-center gap-2 text-brand-soft font-bold text-sm">Meet Good Secrets <ArrowRight className="w-4 h-4"/></Link><Link href="/reviews" className="min-h-11 text-white font-bold text-sm inline-flex items-center">Traveler reviews →</Link></div></div></section>

  {hotels.length>0&&<section className="max-w-7xl mx-auto px-4 sm:px-8 space-y-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full bg-action-soft px-3 py-1.5 text-xs font-bold text-action border border-action-border mb-2">Kenyan resident offers</div><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white">Beach stays and safari extensions</h2><p className="text-base text-on-shell-muted mt-2">Diani, Watamu and Mombasa stays, with dedicated resident pricing where available.</p></div><Link href="/hotels?resident=true" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-brand-soft">Browse stays <ArrowRight className="w-4 h-4"/></Link></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{hotels.slice(0,4).map(h=><HotelCard key={h.id} hotel={h}/>)}</div></section>}

  <section className="max-w-7xl mx-auto px-4 sm:px-8 space-y-8"><div className="text-center max-w-2xl mx-auto space-y-2"><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Not sure where to start?</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white">Build your safari preferences</h2><p className="text-base text-on-shell-muted">Answer a few questions to narrow the route. A human safari planner still helps shape the final itinerary.</p></div><div className="rounded-[2rem] border border-white/10 bg-white/5 p-8 text-center"><Link href="/safari-builder" className="inline-flex min-h-12 px-7 rounded-xl bg-brand-soft text-ink-strong font-extrabold items-center">Start the safari builder</Link></div></section>

  {blogPosts.length>0&&<section className="max-w-7xl mx-auto px-4 sm:px-8 space-y-8"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Plan with confidence</span><h2 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-white mt-1">Stories, guides and practical safari advice.</h2></div><Link href="/blog" className="text-brand-soft font-bold">Travel magazine →</Link></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{blogPosts.slice(0,3).map(p=><article key={p.id} className="rounded-3xl overflow-hidden border border-white/10 bg-white/5"><div className="relative aspect-[16/10]"><Image src={p.featuredImage||'/images/catalog/mara-savannah.jpg'} alt={p.title} fill className="object-cover"/></div><div className="p-5"><span className="text-xs uppercase tracking-widest text-brand-soft font-bold">{p.category}</span><h3 className="font-serif-luxury text-xl text-white mt-2"><Link href={`/blog/${p.slug}`}>{p.title}</Link></h3><p className="text-sm text-on-shell-muted mt-2">{p.excerpt}</p></div></article>)}</div></section>}

  <section className="max-w-7xl mx-auto px-4 sm:px-8"><div className="rounded-[2rem] border border-white/10 bg-white/5 p-8 sm:p-12 grid lg:grid-cols-2 gap-8 items-center"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-soft">Ready when you are</span><h2 className="font-serif-luxury text-3xl sm:text-5xl font-bold text-white mt-2">Bring us your dates, not a finished itinerary.</h2><p className="text-on-shell-muted mt-3">We can help turn a rough safari idea into a route that works on the ground.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><EnquiryButton label="Request a safari plan" className="min-h-12 px-7 rounded-xl bg-brand-soft text-ink-strong font-extrabold"/><Link href="/safari-builder" className="min-h-12 px-7 rounded-xl border border-white/30 text-white font-bold inline-flex items-center">Try the safari builder</Link></div></div></section>
</div>}
